Feature/weighted traversal
arangodb/arangodb pull request #12205
Opened 2020-07-13 09:17 UTC by maierlars

### Scope & Purpose

PR adds a `mode` field to traversal options (deprecating old `bfs: true`) now allowing following value: `dfs` (default), `bfs` and `weighted`. In weighted mode there is now a `weightAttribute` and `defaultWeight` attribute with same semantics as for shortest path traversals. Paths are enumerate by increasing length. Furthermore returned path has a new attribute `weights` that contains the weights at each individual step.

For example:
```
for x, v, p in 0..10 outbound "places/York" graph "kShortestPathsGraph" options {mode: "weighted", weightAttribute: "travelTime", uniqueVertices: "path"}
    FILTER p.edges[*].travelTime ALL < 3
    let totalTime = LAST(p.weights)
    FILTER totalTime < 6
    SORT totalTime DESC
    return {path: p.vertices[*]._key, weight: LAST(p.weights), weights: p.edges[*].travelTime}
```

returns
path | weight | weights
-- | -- | --
["York","London","Birmingham","Carlisle"] | 5.3 | [1.8,2.5,1]
["York","London","Birmingham"] | 4.3 | [1.8,2.5]
["York","London","Brussels"] | 4.3 | [1.8,2.5]
["York","London"] | 1.8 | [1.8]
["York"] | 0 | []

I'd like to ask for your feed back on this. Of course I will add tests later. It should work with all other options like `uniqueVertices` and `uniqueEdges`. Important case `uniqueVertices: "global"` <3

- [x] Strictly *new functionality* (i.e. a new feature / new option, no need for porting)
- [x] The behavior in this PR can be (and was) *manually tested* (support / qa / customers can test it)
- [x] The behavior change can be verified via automatic tests

### Testing & Verification

This PR adds tests that were used to verify all changes:

- [ ] Added new **integration tests** (i.e. in shell_server / shell_server_aql)

Additionally:
- [x] I ensured this code runs with ASan / TSan or other static verification tools

### Documentation

Will add if you like the change.

- [ ] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)
- [ ] Added a new section in the *Manual*

2020-07-13 09:46 UTC, Simran-B commented
> Paths are enumerate by increasing length

That makes `mode: "weighted"` breadth-first, right?

2020-08-31 12:14 UTC, maierlars commented
> > Paths are enumerate by increasing length
> 
> That makes `mode: "weighted"` breadth-first, right?

Could you elaborate on that? There is now "bfs", "dfs" and "weighted". "weighted" without weights is a _slower_ form of "bfs". Did that answer your question?

2020-09-25 13:55 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/11985/

2020-09-28 13:34 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/11995/

2020-09-28 13:42 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/11996/

2020-09-28 15:00 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/11998/

2020-09-28 15:15 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/11999/

2020-09-29 07:28 UTC, maierlars commented
![image](https://user-images.githubusercontent.com/29692726/94526649-17758780-0236-11eb-8e80-8d458118db7d.png)

2020-09-29 12:26 UTC, mchacki requested changes
Just one minor item in the edge cursor.
Which checks 1 depth too much.
Everything else I like very much good job :+1:

2020-09-29 12:26 UTC, mchacki commented on lib/Basics/VelocyPackHelper.h
> +auto unpackTuple(VPackArrayIterator& iter, std::index_sequence<Is...>) {
I like this, very helpful!

2020-09-29 12:26 UTC, mchacki commented on tests/Aql/TraversalExecutorTest.cpp
> +    // Implement
```suggestion
```

I think this is never needed in the test, just to please the API

2020-09-29 12:26 UTC, mchacki commented on tests/js/server/aql/aql-graph-weighted-traversal.js
> +     4 -> 6
Thi is not aligned with data.
6 -> 3 uses wight 0.5 which is missing here.

2020-09-30 14:39 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/12023/

2020-10-01 08:01 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/12032/

2020-10-01 12:25 UTC, maierlars reviewed
foobar

2020-10-02 07:29 UTC, maierlars commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12068/

2020-10-02 08:10 UTC, maierlars commented
Hello world!

2020-10-02 08:22 UTC, maierlars commented
Hello world!

2020-10-02 08:30 UTC, maierlars commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12069/

2020-10-02 09:16 UTC, maierlars commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12070/

2020-10-02 11:22 UTC, maierlars commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12076/

2020-10-02 12:52 UTC, mchacki approved these changes
LGTM

2020-10-02 12:53 UTC, merged