Feature/arangosearch-s2
arangodb/arangodb pull request #12592
Opened 2020-09-01 22:27 UTC by gnusi

### Scope & Purpose

Geo functionality support for ArangoSearch

- [ ] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [ ] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions)*

#### Related Information

*(Please reference tickets / specification etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added **Regression Tests**
  - [ ] Added new C++ **Unit Tests**
  - [ ] Added new **integration tests** (i.e. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)

Additionally:

- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

*(Include link to Jenkins run etc)*

### Documentation

> All new Features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the changelog so that
> developers and users have a concise overview. 

- [ ] Added a *Changelog Entry* (referencing the corresponding public or internal issue number)
- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2020-09-24 15:36 UTC, Dronplane requested changes

2020-09-24 15:36 UTC, Dronplane commented on arangod/Aql/Functions.cpp
> +  static char const* AFN = "IN_GEO_RANGE";
```suggestion
  static char const* AFN = "GEO_IN_RANGE";
```

2020-09-24 15:36 UTC, Dronplane commented on arangod/IResearch/Geo.cpp
> +  } else if (slice.isArray()) {
Maybe just check `slice.isArray() && slice.length() >= 2` right here ? Otherwise we will get true result for array with just one member

2020-09-24 15:36 UTC, Dronplane commented on arangod/IResearch/Geo.cpp
> +
Add logging warning if point is not valid? As all other fail-exits in this function has reason logged.

2020-09-24 16:50 UTC, Dronplane commented on arangod/IResearch/GeoAnalyzer.h
> +  return type.size() > 3 && irs::starts_with(type, "geo");
seems like  kludge ) Maybe use map of exact values ?

2020-09-24 16:50 UTC, Dronplane commented on arangod/IResearch/IResearchFilterFactory.cpp
> +    case SCOPED_VALUE_TYPE_ARRAY: { // [lng, lat] is valid input
Should we at least assert array length here ?

2020-09-24 17:11 UTC, gnusi commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11974/

2020-09-24 17:15 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11975/

2020-09-24 21:09 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11979/

2020-09-25 10:24 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11982/

2020-09-25 11:22 UTC, Dronplane approved these changes
Some more minor checks. LGTM in general

2020-09-25 12:34 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11984/

2020-09-25 15:48 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11987/

2020-09-28 14:14 UTC, gnusi commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11997/

2020-09-28 15:50 UTC, merged