Port chaos lost documents fix to 3.6.
arangodb/arangodb pull request #12606
Opened 2020-09-08 11:43 UTC by neunhoef

2020-09-08 11:44 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11769/

2020-09-11 06:18 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11811/

2020-09-11 08:02 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11812/

2020-09-11 12:13 UTC, goedderz approved these changes
LGTM

2020-09-11 12:18 UTC, neunhoef commented on arangod/Aql/EngineInfoContainerCoordinator.cpp
> +      queryRegistry->insert(_id, &query, ttl, true, false, cluster::CallbackGuard());
This is only legacy code, as far as I see. It is the `/_api/aql/instantiate` API which was pre 3.5.

2020-09-14 14:04 UTC, KVS85 commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11835/

2020-09-14 16:41 UTC, KVS85 commented
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/13492/

2020-09-14 16:43 UTC, KVS85 requested changes
Please observe reproducible failures for MMFiles at `http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/13490/EDITION=community,STORAGE_ENGINE=mmfiles,TEST_SUITE=cluster,limit=(linux&&test)%7C%7Cgce/artifact/testfailures.txt`.

2020-09-17 07:13 UTC, jsteemann commented on arangod/Aql/RestAqlHandler.cpp
> +    RebootId rebootId, std::string coordinatorId) {
Can be passed by const reference, but this is an unimportant optimization here.
```suggestion
    RebootId rebootId, std::string const& coordinatorId) {
```

2020-09-17 07:14 UTC, jsteemann commented on arangod/Aql/RestAqlHandler.h
> +                        RebootId rebootId, std::string coordinatorId);
Can be passed by const reference, but this is an unimportant optimization here.
```suggestion
                        RebootId rebootId, std::string const& coordinatorId);
```

2020-09-17 07:30 UTC, jsteemann commented on arangod/Cluster/Maintenance.cpp
> +              std::map<std::string, std::string>{{std::string(NAME), std::string(CREATE_DATABASE)}, {std::string("tick"), std::to_string(TRI_NewTickServer())},
The "tick" value here will always be unique and will not be equal to the database's id. What's its purpose?
I think it deserves a code comment.

2020-09-17 07:30 UTC, jsteemann commented on arangod/Cluster/Maintenance.cpp
> +          std::map<std::string, std::string>{{std::string(NAME), std::string(DROP_DATABASE)}, {std::string("tick"), std::to_string(TRI_NewTickServer())},
The "tick" value here will always be unique and will not be equal to the database's id. What's its purpose?
I think it deserves a code comment.

2020-09-17 08:05 UTC, jsteemann commented on arangod/Aql/RestAqlHandler.cpp
> +    RebootId rebootId, std::string coordinatorId) {
done

2020-09-17 08:05 UTC, jsteemann commented on arangod/Aql/RestAqlHandler.h
> +                        RebootId rebootId, std::string coordinatorId);
done

2020-09-17 08:05 UTC, jsteemann commented on arangod/Cluster/Maintenance.cpp
> +          std::map<std::string, std::string>{{std::string(NAME), std::string(DROP_DATABASE)}, {std::string("tick"), std::to_string(TRI_NewTickServer())},
tick attribute removed

2020-09-17 08:05 UTC, jsteemann commented on arangod/Cluster/Maintenance.cpp
> +              std::map<std::string, std::string>{{std::string(NAME), std::string(CREATE_DATABASE)}, {std::string("tick"), std::to_string(TRI_NewTickServer())},
tick attribute removed

2020-09-17 08:06 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11869/

2020-09-17 08:28 UTC, jsteemann approved these changes

2020-09-17 12:20 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11874/

2020-09-17 14:09 UTC, KVS85 commented
Tests blue.

2020-09-17 14:09 UTC, KVS85 approved these changes

2020-09-17 14:14 UTC, merged