Port bugfix for chaos lost documents to 3.5.
arangodb/arangodb pull request #12636
Opened 2020-09-11 10:01 UTC by neunhoef

2020-09-11 10:03 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/11815/

2020-09-15 11:30 UTC, goedderz requested changes
I'm missing the change in `arangod/Aql/EngineInfoContainerDBServerServerBased.cpp` that adds the rebootId to the request.

2020-09-17 08:26 UTC, jsteemann commented on arangod/Cluster/Maintenance.cpp
> +              std::map<std::string, std::string>{{std::string(NAME), std::string(CREATE_DATABASE)}, {std::string("tick"), std::to_string(TRI_NewTickServer())},
```suggestion
              std::map<std::string, std::string>{{std::string(NAME), std::string(CREATE_DATABASE)},
```

2020-09-17 08:27 UTC, jsteemann commented on arangod/Cluster/Maintenance.cpp
> +          std::map<std::string, std::string>{{std::string(NAME), std::string(DROP_DATABASE)}, {std::string("tick"), std::to_string(TRI_NewTickServer())},
```suggestion
          std::map<std::string, std::string>{{std::string(NAME), std::string(DROP_DATABASE)}, 
```

2020-09-17 08:28 UTC, jsteemann approved these changes

2020-09-17 09:23 UTC, jsteemann commented
@goedderz : I added the missing part. Can you recheck? Thanks!

2020-09-17 10:16 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11872/

2020-09-17 10:43 UTC, goedderz approved these changes
LGTM

2020-09-17 12:22 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11875/

2020-09-17 14:26 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11881/

2020-09-17 15:54 UTC, jsteemann commented
Tests blue

2020-09-17 19:03 UTC, KVS85 approved these changes

2020-09-17 19:04 UTC, merged