Add truncate context for audit logging
arangodb/arangodb pull request #12643
Opened 2020-09-11 16:22 UTC by danielhlarkin

### Scope & Purpose

Fix mistaken "internal" audit logging for truncate operation

- [x] :hankey: Bugfix 
- [ ] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [ ] :book: CHANGELOG entry made
- [ ] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required
- [ ] Backports required for:

Enterprise component: 

Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11823/

2020-09-12 10:52 UTC, graetzer requested changes
So was the options thing default constructed ? Where are the tests that catch this?

2020-09-14 07:58 UTC, jsteemann commented on arangod/Cluster/ClusterMethods.cpp
> +    OperationOptions const options = OperationOptions()) {
Is this intentionall passed by value? I also would prefer to not use default function parameters, as it makes it easy to overlook necessary changes at call sites.
```suggestion
    OperationOptions const& options) {
```

2020-09-14 08:00 UTC, jsteemann commented
LGTM in general, but I also think we should have tests in place that verify the correct logging of the user name (vs. "internal") in case we are dealing with incoming HTTP/VST requests.

2020-09-14 09:09 UTC, graetzer commented
please change the OptionsResult constructor so we do not miss passing the options in
```bash
diff --git a/arangod/Utils/OperationResult.h b/arangod/Utils/OperationResult.h
index a5e429beaae..78e619ecbdc 100644
--- a/arangod/Utils/OperationResult.h
+++ b/arangod/Utils/OperationResult.h
@@ -67,7 +67,7 @@ struct OperationResult final {
 
   // create result with details
   OperationResult(Result result, std::shared_ptr<VPackBuffer<uint8_t>> buffer,
-                  OperationOptions options = {},
+                  OperationOptions options,
                   std::unordered_map<int, size_t> countErrorCodes = std::unordered_map<int, size_t>())
       : result(std::move(result)),
         buffer(std::move(buffer)),
```

2020-09-15 22:54 UTC, danielhlarkin commented
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11855/

2020-09-17 15:27 UTC, jsteemann commented on arangod/Agency/Constituent.cpp
> +      res = trx.finish(result.errorNumber());
```suggestion
      res = trx.finish(result.result);
```

2020-09-17 15:28 UTC, jsteemann commented on arangod/Agency/Constituent.cpp
> +      res = trx.finish(result.errorNumber());
Seems like there isn't (and never was) any code that would check `res` afterwards. 
An exception is caught here, but if there is no exception, `res` can still contain an error. :thinking:

2020-09-17 15:31 UTC, jsteemann commented on arangod/Agency/State.cpp
> +    OperationResult logResult = trx.insert("log", log.slice(), _options);
There isn't (and never was) any check for the value of `logResult`. So it may go wrong and this will not be noticed.

2020-09-17 15:32 UTC, jsteemann commented on arangod/Agency/State.cpp
> +    OperationResult logResult = trx.insert("log", log.slice(), _options);
I guess we should bail out in that case as well.

2020-09-17 15:35 UTC, jsteemann commented on arangod/Aql/SingleRemoteModificationExecutor.cpp
>    OperationOptions& options = _info._options;
is the `options` variable needed here at all? it seems that the following code refers to `_info._options` instead.

2020-09-17 15:41 UTC, jsteemann commented on arangod/Graph/GraphOperations.cpp
> +                             std::string{TRI_errno_string(TRI_ERROR_GRAPH_VERTEX_COL_DOES_NOT_EXIST)}));
```suggestion
    return Result(TRI_ERROR_GRAPH_VERTEX_COL_DOES_NOT_EXIST,
                         vertexCollectionName + " " +
                             std::string{TRI_errno_string(TRI_ERROR_GRAPH_VERTEX_COL_DOES_NOT_EXIST)});
```

2020-09-17 17:24 UTC, jsteemann commented on arangod/Agency/State.cpp
>    }
```suggestion
    OperationResult logResult = trx.insert("log", log.slice(), _options);
    if (logResult.fail()) {
      THROW_ARANGO_EXCEPTION(logResult.result);
    }
    OperationResult confResult =
        trx.replace("configuration", configuration.slice(), _options);
    res = trx.finish(confResult.result);
  } catch (std::exception const& e) {
    LOG_TOPIC("ced35", ERR, Logger::AGENCY) << "Failed to persist log entry: " << e.what();
    return false;
  }
```

2020-09-17 17:43 UTC, danielhlarkin commented
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/11886/

2020-09-18 04:47 UTC, graetzer commented on arangod/Agency/Constituent.cpp
> +      res = trx.finish(result.result);
❤️

2020-09-18 04:52 UTC, graetzer approved these changes
well done!

2020-09-18 09:23 UTC, merged