more metrics
arangodb/arangodb pull request #12663
Opened 2020-09-16 12:02 UTC by jsteemann

### Scope & Purpose

* Added replication metrics `arangodb_replication_initial_sync_bytes_received` for the number of bytes received during replication initial sync operations and `arangodb_replication_tailing_bytes_received` for the number of bytes received for replication tailing requests. Also added `arangodb_replication_failed_connects` to track the number of connection failures or non-OK response during replication.
* Added metrics `rocksdb_free_inodes` and `rocksdb_total_inodes` to track the number of free inodes and the total/maximum number of inodes for the file system the RocksDB database directory is located in. These metrics will always be 0 on Windows.

- [ ] :hankey: Bugfix 
- [x] :pizza: New feature 
- [ ] :hammer: Refactoring 
- [x] :book: CHANGELOG entry made
- [x] :muscle: The behavior in this PR was *manually tested*
- [ ] :computer: The behavior change can be verified via automatic tests

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions)*

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/11861/

2020-09-16 12:18 UTC, ajanikow approved these changes
LGTM

2020-09-16 14:28 UTC, Simran-B requested changes
Should be prefixed `arangodb_rocksdb_` not `rocksdb_`

2020-09-16 14:32 UTC, Simran-B commented
https://github.com/arangodb/docs/pull/551

2020-09-16 14:34 UTC, jsteemann commented
@Simran-B : I understand that request, but this would also change the names of the existing rocksdb metrics in ArangoDB.
The metrics names are auto-generated by a single function, and if I change it, all existing consumers of the rocksdb metrics would get a "No data":
https://github.com/arangodb/arangodb/blob/devel/arangod/RocksDBEngine/RocksDBEngine.cpp#L2163-L2174

2020-09-17 09:22 UTC, dothebart approved these changes

2020-09-17 09:54 UTC, jsteemann commented
Tests blue

2020-09-17 09:55 UTC, merged