Ensure failoverCandidates have no servers not in Plan.
arangodb/arangodb pull request #12803
Opened 2020-10-08 09:07 UTC by neunhoef

Fix failoverCandidates for servers not in Plan.

Problem: we must never fail over to a server which is not in Plan
because it might not have the data.

ToDo:

 - [X] AddFollower, FailedFollower, CleanOutServer and MoveShard will not
       add a server to the Plan which is in failoverCandidates for this
       shard or any of the ones with distributeShardsLike.
 - [X] add preconditions to ensure that it is snapshot-safe
 - [X] make dbserver Maintenance remove servers that are not in Plan from 
       failoverCandidates.

2020-10-08 09:07 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12183/

2020-10-08 10:22 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12189/ new try after fixing compilation.

2020-10-08 11:22 UTC, mchacki requested changes
Code LGTM.

But we are loosing one static string here, see comment

2020-10-08 11:22 UTC, mchacki commented on arangod/Cluster/Maintenance.cpp
> +            VPackSlice serverList = lcol.get("servers");
```suggestion
            VPackSlice serverList = lcol.get(SERVERS);
```

2020-10-08 15:17 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12205/

2020-10-08 15:17 UTC, KVS85 commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12205/

2020-10-08 16:57 UTC, KVS85 commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12212/

2020-10-08 21:03 UTC, KVS85 commented
Tests blue.

2020-10-09 08:58 UTC, KVS85 approved these changes

2020-10-09 09:09 UTC, merged