Ensure failoverCandidates have no servers not in Plan.
arangodb/arangodb pull request #12804
Opened 2020-10-08 10:25 UTC by neunhoef

Fix failoverCandidates for servers not in Plan.

Problem: we must never fail over to a server which is not in Plan
because it might not have the data.

TODO:

 - [X] AddFollower, FailedFollower, CleanOutServer and MoveShard will not
       add a server to the Plan which is in failoverCandidates for this
       shard or any of the ones with distributeShardsLike.
 - [X] add preconditions to ensure that it is snapshot-safe
 - [X] make dbserver Maintenance remove servers that are not in Plan from
       failoverCandidates.

2020-10-08 10:26 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12191/

2020-10-08 11:20 UTC, mchacki requested changes
Code LGTM.
But we are loosing one static string here, see my suggestion

2020-10-08 11:20 UTC, mchacki commented on arangod/Cluster/Maintenance.cpp
> +            VPackSlice serverList = lcol.get("servers");
```suggestion
            VPackSlice serverList = lcol.get(SERVERS);
```

2020-10-08 13:59 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12198/

2020-10-08 14:01 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12200/

2020-10-08 15:16 UTC, neunhoef commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12203/

2020-10-08 15:47 UTC, mchacki approved these changes
LGTM

2020-10-09 09:33 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12220/

2020-10-28 16:40 UTC, mchacki commented
Retry Jenkins after devel merge
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12531/

2020-10-29 08:34 UTC, mchacki commented
The red test in Jenkins seems unrelated, I am investigating it now.
All other tests blue.

2020-10-29 11:09 UTC, mchacki commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12540/
Jenkins Blue, red test above is unrelated we work on it separately

2020-10-29 11:09 UTC, merged