make compacting while truncating optional
arangodb/arangodb pull request #12857
Opened 2020-10-13 15:15 UTC by dothebart

compacting is resource intensive. This makes truncate an expensive operation. Make it configurable.

2020-10-14 08:29 UTC, dothebart commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr-linux/13885/

2020-10-14 09:38 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12289/ with modified tests.

2020-10-14 10:15 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12290/ *gna

2020-10-14 11:50 UTC, graetzer commented
why yet another option, shouldn't compact only run if its removed substantial data ?

2020-10-14 11:53 UTC, dothebart commented
how do you detect that in the cluster usecase? 
These invocations would make tests on spinning disks worse. Since this is only a magnifier, and most tests don't care for saved disk-space even after truncating 1000 documents, letting the application control this is the better way. 
In the end we still have the direct way to invoke `compact` on a collection?

2020-10-14 12:11 UTC, goedderz requested changes
Thanks for the PR, this is really expedient.

2020-10-14 12:11 UTC, goedderz commented on js/server/modules/@arangodb/arango-collection.js
> +  var ret = this.TRUNCATE(options.compact);
You add handling for `waitForSync` here, like in the `js/client` code - seems good to make this consistent. However, `waitForSync` is never passed to `TRUNCATE` and just ignored.

2020-10-14 12:11 UTC, goedderz commented on js/server/modules/@arangodb/arango-collection.js
>    }
This isn't needed anymore, as `TRUNCATE` does it already. And as far as I can see, the `ArangoCollection` implementation in `v8-collection.cpp` doesn't even have a `compact` method (which probably should be added, as the client-side `ArangoCollection` has it).

2020-10-14 12:11 UTC, goedderz commented on js/client/modules/@arangodb/arango-collection.js
>    this._status = null;
Below this comments, the function ends with
```
  if (!options.compact) {
    return;
  }
```
. That seems to be a relict, can you remove it?

2020-10-14 12:24 UTC, dothebart commented on arangod/V8Server/v8-collection.cpp
> +  opOptions.truncateCompact = ExtractBooleanArgument(isolate, args, 1, true);
the V8 wrapper in `js/server/modules/@arangodb/arango-collection.js` doesn't use this. Its probably a remaint from the time when the handlers were done in .js

2020-10-14 12:50 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12299/

2020-10-14 13:59 UTC, Simran-B approved these changes

2020-10-15 04:43 UTC, dothebart commented
tests green.

2020-10-15 19:13 UTC, jsteemann requested changes

2020-10-15 19:13 UTC, jsteemann commented on Documentation/DocuBlocks/Rest/Collections/put_api_collection_truncate.md
> +document create, update, replace or removal operation (default: *false*)
```suggestion
If *true* then the data is synchronized to disk before returning from the
truncate operation (default: *false*)
```

2020-10-15 19:13 UTC, jsteemann commented on Documentation/DocuBlocks/Rest/Collections/put_api_collection_truncate.md
> +in order to free up disk space. This can be resource intense. If the only
```suggestion
in order to free up disk space. This can be resource intensive. If the only 
```

2020-10-15 19:13 UTC, jsteemann commented on arangod/V8Server/v8-collection.cpp
> +  opOptions.isSynchronousReplicationFrom = ""; // not specified anymore.
This is empty by default anyway, so we can omit assigning the empty string to it.
```suggestion
```

2020-10-15 19:13 UTC, jsteemann commented on js/client/modules/@arangodb/arango-collection.js
> +  append += (append === '')? '?':'&' + (options.compact ? 'compact=true' : 'compact=false');
It looks like the generated URL will have a wrong format if only `waitForSync` is specified.
This is unrelated to this PR, but we should fix it as well:
```suggestion
  var append = (options.waitForSync ? '?waitForSync=true' : '');
  append += (append === '') ? '?' : '&' + (options.compact ? 'compact=true' : 'compact=false');
```

2020-10-15 19:13 UTC, jsteemann commented on js/server/modules/@arangodb/arango-collection.js
>  };
I think this entire function and be removed, as it is only a wrapper for calling the internal TRUNCATE function.
And we should renamed the internal TRUNCATE v8 binding to just truncate, so it replaces this function here.

2020-10-16 09:17 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12333/

2020-10-16 09:18 UTC, jsteemann commented on arangod/V8Server/v8-collection.cpp
> +  if (args[0]->IsObject()) {
This does not check that there is at least one argument in `args`, so it may crash here.

2020-10-16 09:18 UTC, jsteemann commented on arangod/V8Server/v8-collection.cpp
> + TRI_ASSERT(args.Length() > 2);
```suggestion
  TRI_ASSERT(args.Length() > 2);
```

2020-10-16 09:19 UTC, jsteemann commented on arangod/V8Server/v8-collection.cpp
> +                                          OperationOptions &options,
```suggestion
                                          OperationOptions& options,
```

2020-10-16 09:50 UTC, jsteemann approved these changes
LGTM

2020-10-16 10:42 UTC, goedderz commented on arangod/V8Server/v8-collection.cpp
> +  opOptions.truncateCompact = ExtractBooleanArgument(isolate, args, 1, true);
@dothebart Or it was just forgotten there.

2020-10-16 11:17 UTC, dothebart commented on arangod/V8Server/v8-collection.cpp
> +  opOptions.truncateCompact = ExtractBooleanArgument(isolate, args, 1, true);
the wrapper is history now, its only inside c++ now.

2020-10-16 14:26 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12335/

2020-10-16 16:14 UTC, dothebart commented
tests blue.

2020-10-16 16:15 UTC, merged