noob friendly error messages
arangodb/arangodb pull request #12873
Opened 2020-10-19 11:23 UTC by dothebart

2020-10-19 11:53 UTC, jsteemann requested changes
Let's also please change the PR title.

2020-10-19 11:53 UTC, jsteemann commented on arangosh/Shell/ClientFeature.cpp
> +  if (_endpoint.find("0.0.0.0") != std::string::npos) {
This will also complain about `10.0.0.0`, which is probably not correct.

2020-10-19 11:53 UTC, jsteemann commented on arangosh/Shell/ClientFeature.cpp
> +      "') - 0.0.0.0 is only allowed for servers binding any." <<
To be honest, I don't understand the error message "0.0.0.0 is only allowed for servers binding any".
Can we phrase it?

2020-10-19 11:53 UTC, jsteemann commented on arangosh/Shell/ClientFeature.cpp
> +      "') - :: is only allowed for servers binding any." <<
Mmh, we are complaining about `::` (two colons) but are checking for `:::` (three colons) before? Is that intentional?
Again, I personally don't understand the error message, so I would suggest rephrasing it.

2020-10-19 13:34 UTC, jsteemann requested changes

2020-10-19 13:34 UTC, jsteemann commented on lib/Endpoint/EndpointIpV4.cpp
> +bool EndpointIpV4::isBroadcastBind() {
```suggestion
bool EndpointIpV4::isBroadcastBind() const {
```

2020-10-19 13:34 UTC, jsteemann commented on lib/Endpoint/EndpointIpV4.h
> +  virtual bool isBroadcastBind();
```suggestion
  bool isBroadcastBind() override const;
```

2020-10-19 13:34 UTC, jsteemann commented on lib/Endpoint/EndpointIpV6.cpp
> +bool EndpointIpV6::isBroadcastBind() {
```suggestion
bool EndpointIpV6::isBroadcastBind() const {
```

2020-10-19 13:34 UTC, jsteemann commented on lib/Endpoint/EndpointIpV6.h
> +  virtual bool isBroadcastBind();
```suggestion
  bool isBroadcastBind() const override;
```

2020-10-19 13:34 UTC, jsteemann commented on arangosh/Shell/ClientFeature.cpp
> +      " Choose a public IP address of your machine instead." <<
```suggestion
      " Choose an IP address of your machine instead." <<
```

2020-10-19 14:00 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12360/

2020-10-19 14:01 UTC, jsteemann approved these changes
LGTM

2020-10-19 14:41 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12361/

2020-10-19 17:53 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12367/

2020-10-21 07:06 UTC, dothebart commented
tests blue.

2020-10-21 08:06 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12380/

2020-10-21 08:07 UTC, jsteemann approved these changes

2020-10-21 08:07 UTC, merged