don't attempt to client-bind Broadcast Bind addresses (#12873)
arangodb/arangodb pull request #12886
Opened 2020-10-21 08:34 UTC by dothebart

backport of https://github.com/arangodb/arangodb/pull/12873

2020-10-21 08:35 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12388/

2020-10-21 10:08 UTC, dothebart commented
tests blue except for known garbage collection issue in `server_permissions`.

2020-10-21 10:47 UTC, jsteemann approved these changes

2020-10-27 11:54 UTC, jsteemann commented on arangosh/Shell/ClientFeature.cpp
> +    if (endpoint.get() == nullptr) {
apparently this breaks VST client connections, so we should change this first before we merge it.

2020-10-27 11:54 UTC, jsteemann requested changes
This change will break VST connections via the arangosh.

2020-10-27 16:36 UTC, jsteemann commented on arangosh/Shell/ClientFeature.cpp
> +    if (endpoint.get() == nullptr) {
Fixed

2020-10-27 16:37 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12484/

2020-10-27 16:37 UTC, jsteemann approved these changes

2020-10-28 10:25 UTC, dothebart reviewed
lgtm

2020-10-28 21:11 UTC, KVS85 commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12534/

2020-10-29 06:29 UTC, KVS85 commented
Tests blue.

2020-10-29 06:29 UTC, merged