Bug fix 3.6/cleanup 20201117
arangodb/arangodb pull request #13049
Opened 2020-11-17 01:50 UTC by jsteemann

### Scope & Purpose

This is a multi-purpose PR:

It makes the number of network I/O threads properly configurable via the startup option `--network.io-threads`. This option existed before, but its configured value was effectively clamped to a value of `1`. 
This change requires forward ports to 3.7 and devel.

It also disables cluster maintenance background threads on coordinators.
The maintenance threads don't have any purpose on coordinators, so there is no need to start them there. This saves 2 or more background threads on coordinators. These threads should have mostly been idle before, so saving them will not have a huge impact except saving a few MB of thread stack memory.
The maintenance threads are already turned off on coordinators in 3.7 and devel for a while, so this does not need to be ported.

In addition this PR removes the `_allowDirectExecution` instance variable from RestHandlers, which in 3.6 was only set but never read back. This variable lost its meaning at point in the 3.5 cycle, so it is now useless and can be removed.
The instance variable has already been removed in 3.7 and devel a while ago, so this does not need to be ported.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12786/

2020-11-17 01:56 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12788/

2020-11-17 14:14 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12803/

2020-11-17 15:09 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/12806/

2020-11-17 21:47 UTC, neunhoef requested changes
LGTM. I found one LOG_DEVEL, which should be removed.

2020-11-17 21:47 UTC, neunhoef commented on arangod/Network/NetworkFeature.cpp
> +  LOG_DEVEL << "NUM: " << _numIOThreads;
This should be removed before merging.

2020-11-17 21:52 UTC, jsteemann commented on arangod/Network/NetworkFeature.cpp
> +  LOG_DEVEL << "NUM: " << _numIOThreads;
```suggestion
```

2020-11-18 07:09 UTC, fceller approved these changes

2020-11-18 12:13 UTC, KVS85 approved these changes
LGTM.

2020-11-18 12:13 UTC, merged