Bug fix/executionblockimpl hasmore assertion
arangodb/arangodb pull request #13094
Opened 2020-11-25 16:37 UTC by mchacki

### Scope & Purpose

This PR fixes a false assertion in AQL ExecutionBlocks.
The assertion tests that something should be written in an AQL block if an executor is finished with it's work and claims there is even more data available.
This assertion tested for the actually existence of a value entry. If this value is NOT used later, it could actually be optimized away here, causing this assertion to trigger. (An empty row is written, but no value)
Now using the number of written rows.
This covers empty rows as well.

This PR does NOT change any production behavior and therefor has no CHANGELOG entry. The code modified here is not compiled into our release.

Jenkins:
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/12883/

2020-11-25 16:43 UTC, Dronplane requested changes

2020-11-25 16:43 UTC, Dronplane commented on tests/js/server/aql/aql-shadowrow-block-return-regression.js
> +      const query = `FOR d IN hv LET p = (RETURN 1 + 1) RETURN 1`;
```suggestion
      const query = `FOR d IN hv OPTIONS {waitForSync:true} LET p = (RETURN 1 + 1) RETURN 1`;
```
Without this we could end up with less than batch size records in view,  hence violating test`s prerequisites

2020-11-25 16:47 UTC, Dronplane commented on tests/js/server/aql/aql-shadowrow-block-return-regression.js
> +      const res = db._query(query, {}, {optimizer: {rules: ["-all", "+spliced-subqueries"] }});
```suggestion
      const res = db._query(query, {}, {optimizer: {rules: ["+spliced-subqueries"] }});
```
We still need to run ArangoSearch optimization rules

2020-11-26 08:33 UTC, Dronplane commented on tests/js/server/aql/aql-shadowrow-block-return-regression.js
> +      const res = db._query(query, {}, {optimizer: {rules: ["-all", "+spliced-subqueries"] }});
Just checked - I`m wrong. no materialization is hadled by `handle-arangosearch-views` rule which is non-disablable. So It is ok to have -all

2020-11-26 08:38 UTC, Dronplane approved these changes
LGTM

2020-11-26 14:45 UTC, mchacki commented
Latest Jenkins:
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/12890/

Full blue.

2020-11-26 14:46 UTC, merged