make storage engine report its health to the agency
arangodb/arangodb pull request #13288
Opened 2020-12-22 15:27 UTC by jsteemann

### Scope & Purpose

Make DB servers report storage engine errors to the agency, via a new "healthy" attribute in sent to requests to Sync/ServerStates/<id>. The supervision will check this attribute if it is posted, and if it contains a value of `false`, will mark the server as BAD.
DB server health is currently determined by whether or not the storage engine (RocksDB) has reported a background error, and by whether or not the free disk space has reached a critical low amount. The current threshold for free disk space is set at 2% of the disk capacity (the disk is considered that contains the RocksDB database directory).

Failed servers are now reported consistently in the web interface, at approximately the same time in the navigation bar and in the nodes view. Previously these two places had their own, independent poll mechanism for the nodes' health, and they were updated independently, which could cause an inconsistent view of the nodes' availability. Using only one poll mechanism instead also saves some period background requests for the second availability check.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [x] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new **integration tests** (e.g. in shell_client)

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13358/

2020-12-22 20:01 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13362/

2020-12-22 23:54 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13366/

2020-12-23 08:33 UTC, neunhoef requested changes
This is a good start. I would like to see a reason for unhealthiness sent to the agency. Yes, for now we only have the disk space and RocksDB, but already this would be helpful to distinguish. However, so far the unhealthiness report only ends up in the transient store. We should at least forward it on change to the persisted Raft log under `/arango/Supervision/Health` such that it gains visibility in the Health API.
Furthermore, we must not log an error even every 30 seconds, since JPMC will generate a ticket for their DB admin team for *every* single ERROR line in our logs.

2020-12-23 08:33 UTC, neunhoef commented on arangod/Agency/AgencyComm.cpp
> +    builder.add("healthy", VPackValue(isHealthy));
How about adding a string in addition to describing the actual problem?

2020-12-23 08:33 UTC, neunhoef commented on arangod/RocksDBEngine/RocksDBEngine.cpp
> +  bool lastCheckLongAgo = (now - _lastHealthCheckTimestamp > std::chrono::seconds(30));
I doubt JPMC will like this. They create a ticket for their DB admin team for every ERROR log line we write. So if something happens, they wake up in the morning with lots of tickets. Maybe we have to build an exponential backoff here.

2020-12-23 08:33 UTC, neunhoef commented on arangod/RocksDBEngine/RocksDBEngine.cpp
> +  bool lastCheckLongAgo = (now - _lastHealthCheckTimestamp > std::chrono::seconds(30));
At least the log message is always the same ID.

2020-12-23 08:33 UTC, neunhoef commented on arangod/Agency/Supervision.cpp
> +        if (elapsed.count() <= _okThreshold /*&& isHealthy*/) {
Even if we do not declare the server FAILED, we could still report any change in the `isHealthy` flag to the persisted Raft log under `/arango/Supervision/Health` and thus export it to the normal health check API. We would have to adjust `diffStat` in this file and write changes to Raft.

2020-12-23 13:54 UTC, neunhoef commented on arangod/RocksDBEngine/RocksDBEngine.cpp
> +  bool lastCheckLongAgo = (now - _lastHealthCheckTimestamp > std::chrono::seconds(30));
Let's increase the 30 seconds to 24h.

2020-12-23 13:56 UTC, neunhoef approved these changes
LGTM for now, we will continue this work in https://arangodb.atlassian.net/browse/AR-117

2020-12-23 23:55 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13390/

2020-12-23 23:57 UTC, jsteemann commented
DB servers now send a "health" attribute to the agency with more data.
There is also code in the supervision to read such data from "health" if it is posted, but currently nothing happens with the data that is read. In the future, the supervision could pick up this data and use it for its decisions to mark as server as BAD or FAILED.

2020-12-24 01:07 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13392/

2021-01-04 13:03 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13463/

2021-01-04 15:24 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13466/

2021-01-04 17:05 UTC, merged