Make internal ClusterInfo::getPlan() wait for initial plan load from agency
arangodb/arangodb pull request #13291
Opened 2020-12-22 23:47 UTC by jsteemann

### Scope & Purpose

Otherwise the maintenance, fired off by the heartbeat thread, may not wait for the initial data to arrive from the agency, which can cause Plan and Current to be empty when maintenance starts.
No backport for 3.6 is needed, as 3.6 has blocking agency communication here in case the Plan is not there.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *mini chaos*.

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13365/

2020-12-23 02:54 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13369/

2020-12-23 10:10 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13373/

2020-12-23 11:21 UTC, KVS85 commented
Tests blue.

2020-12-23 14:23 UTC, neunhoef requested changes

2020-12-23 14:23 UTC, neunhoef commented on arangod/Cluster/ClusterInfo.cpp
> -  waitForPlan(1);
We also need to address `waitForCurrent` calls, I found another one with forgotten `.wait()` or `.get()`, it is in line 5054.

2020-12-23 14:58 UTC, neunhoef reviewed
Just for the record, here is how it is supposed to work at server start:
  1. AgencyCache and its thread starts polling from the agency. Since it does not have a State yet, it is guaranteed to get the latest snapshot and all that follows it.
  2. The PlanSyncer and CurrentSyncer in `ClusterInfo` request a local callback from AgencyCache whenever /arango/Plan/Version or /arango/Current/Version respectively change, this triggeres `loadPlan` and `loadCurrent` eventually.
  3. `loadPlan` and `loadCurrent` are the only ones which change `_planIndex`, `_planVersion`, `_currentVersion`, `_currentIndex` in `ClusterInfo`.
  4. `getPlan` and `getCurrent` are protected with a `waitForPlan(1).get()` and `waitForCurrent(1).get()` respectively. So nobody outside can get a plan or a current from `ClusterInfo` before it is set up correctly.
  5. Additionally, the `ClusterFeature::start` method has a `waitFor(1).get()` call such that this does not proceed unless the AgencyCache has got a first delivery from the agency, which will already be reasonably up to date. This is all before it even starts the HeartbeatThread (running Maintenance) and the Syncers.
  6. The SyncerThreads do a `loadPlan` or `loadCurrent` respectively before they begin their main loop.

2020-12-23 15:36 UTC, neunhoef approved these changes
LGTM. Further to my previous comment: It is safe to throw in `getPlan` and `getCurrent` when we are shutting down. This is caught in the `run` method of the `HeartbeatBackgrounThread` (which does maintenance via `DBServerAgencySync`) and the shutdown will then work properly. Furthermore, we will not do a maintenance run in this case, even if this is the very first run.

2020-12-23 15:37 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13381/

2020-12-23 19:10 UTC, KVS85 commented
`IResearch*` unit tests are broken in the last run.

2020-12-24 02:48 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13394/

2020-12-24 11:56 UTC, KVS85 commented
Tests blue.

2020-12-24 11:57 UTC, KVS85 approved these changes
LGTM.

2020-12-24 12:36 UTC, fceller approved these changes
LGTM

2020-12-24 13:00 UTC, merged