restrict some global JavaScript objects
arangodb/arangodb pull request #13340
Opened 2021-01-06 21:52 UTC by jsteemann

### Scope & Purpose

* Removed server-side JavaScript object `ArangoClusterComm`, so it cannot be used from inside JavaScript operations or Foxx. The `ArangoClusterComm` object was previously used inside a few internal JavaScript operations, but was not part of the public APIs.

* Restrict access to functions inside JavaScript objects `ArangoAgency` and `ArangoAgent` to JavaScript code that is running in privileged mode, i.e. via the server's emergency console, the `/_admin/execute` API (if turned on) or internal bootstrap scripts.

* Added startup option `--javascript.transactions` to allow turning off JavaScript transactions if not needed. The default value for this option is `true`, meaning JavaScript transactions are available as before. However, using this option they can be turned off by admins to limit the amount of JavaScript user code that is executed.

It is still unclear to what extend this should or can be backported.

This still lacks a few more tests, which will be added soon.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

- [x] Docs PR: TO DO

### Testing & Verification

- [x] The behavior in this PR was *manually tested*
- [x] This change is already covered by existing tests, such as *all*.
- [x] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [x] Added new **integration tests** (e.g. in server_permissions)

Link to Jenkins PR run:
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13489/

2021-01-11 15:56 UTC, jsteemann commented
Tests blue

2021-01-11 17:14 UTC, mchacki requested changes
I am missing two statistic methods now.
I am not unsure if they are obsolete or still used by UI.
If those two questions are sorted out I am very happy with this PR good work :+1:
Technically this is good

2021-01-11 17:14 UTC, mchacki commented on js/common/modules/@arangodb/graph/traversal.js
> +  var useBuiltIn = require('internal').isArangod();
THis is a much better test :+1:

2021-01-11 17:14 UTC, mchacki commented on js/apps/system/_admin/aardvark/APP/statistics.js
> -router.get("/long", function (req, res) {
I am missing replacements for this function.
Is it not used by the UI anymore?

2021-01-11 17:14 UTC, mchacki commented on js/apps/system/_admin/aardvark/APP/statistics.js
> -  if (!cluster.isCoordinator()) {
I am missing replacements for this function.
Is it not used by the UI anymore?

2021-01-11 17:43 UTC, mchacki approved these changes
Ok talked via Chat.
Sorted my comments out 👍 all good.

2021-01-11 18:28 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13558/

2021-01-11 19:01 UTC, jsteemann commented on arangod/V8Server/V8DealerFeature.cpp
> +  LOG_DEVEL << "JS ENABLED!";
```suggestion
```

2021-01-11 19:59 UTC, jsteemann commented
Tests blue again

2021-01-12 07:40 UTC, mchacki approved these changes
LGTM

2021-01-12 09:14 UTC, merged