add read/write metrics
arangodb/arangodb pull request #13383
Opened 2021-01-14 13:51 UTC by kvahed

### Scope & Purpose

Added general read / write io counters to metrics
Added histograms for runtimes in RocksDB for read, insert, replace, update, remove
Added queue time and full URL to HttpCommTask end trace output

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-01-25 12:18 UTC, jsteemann commented on arangod/GeneralServer/VstCommTask.cpp
> +  double const queueTime = stat.ELAPSED_WHILE_QUEUED();
These lines seem unnecessary now.
```suggestion
```

2021-01-25 12:18 UTC, jsteemann commented on arangod/Scheduler/SupervisedScheduler.cpp
> +   uint64_t jobsDone = _jobsDone.load(std::memory_order_acquire);
```suggestion
  uint64_t jobsDone = _jobsDone.load(std::memory_order_acquire);
```

2021-01-25 12:19 UTC, kvahed commented on arangod/GeneralServer/VstCommTask.cpp
> +  double const queueTime = stat.ELAPSED_WHILE_QUEUED();
Outdated. Sorry. Oversight

2021-01-25 12:23 UTC, jsteemann approved these changes

2021-01-27 16:38 UTC, jsteemann commented on arangod/RestServer/MetricsFeature.cpp
> +                     "turn metrics for doiument read/write metrics on or off",
```suggestion
                     "turn metrics for document read/write metrics on or off",
```

2021-01-27 16:38 UTC, jsteemann commented on arangod/RestServer/MetricsFeature.cpp
> +                     .setIntroducedIn(30706);
```suggestion
                     .setIntroducedIn(30707);
```

2021-01-27 16:40 UTC, jsteemann commented on arangod/RocksDBEngine/RocksDBCollection.cpp
> +  ::WriteTimeTracker timeTracker(_statistics._rocksdb_insert_sec, _statistics, options);
```suggestion
  ::WriteTimeTracker timeTracker(_statistics._rocksdb_update_sec, _statistics, options);
```

2021-01-27 16:40 UTC, jsteemann commented on arangod/RocksDBEngine/RocksDBCollection.cpp
> +  ::WriteTimeTracker timeTracker(_statistics._rocksdb_insert_sec, _statistics, options);
```suggestion
  ::WriteTimeTracker timeTracker(_statistics._rocksdb_replace_sec, _statistics, options);
```

2021-01-27 16:40 UTC, jsteemann commented on arangod/RocksDBEngine/RocksDBCollection.cpp
> +  ::WriteTimeTracker timeTracker(_statistics._rocksdb_insert_sec, _statistics, options);
```suggestion
  ::WriteTimeTracker timeTracker(_statistics._rocksdb_remove_sec, _statistics, options);
```

2021-01-27 16:40 UTC, jsteemann commented on arangod/RocksDBEngine/RocksDBCollection.cpp
> +  ::WriteTimeTracker timeTracker(_statistics._rocksdb_insert_sec, _statistics, options);
```suggestion
  ::WriteTimeTracker timeTracker(_statistics._rocksdb_remove_sec, _statistics, options);
```

2021-01-27 16:42 UTC, jsteemann requested changes
Currently the write operations update the wrong metrics.

We should also backport the tests for the new startup option in `tests/js/client/server_parameters`.

2021-01-27 16:57 UTC, kvahed commented
Committed all suggestion. Dangerous auto-merge!

2021-01-27 17:02 UTC, jsteemann approved these changes

2021-02-02 14:09 UTC, jsteemann commented on arangod/RestServer/MetricsFeature.cpp
> +                     .setIntroducedIn(30707);
```suggestion
                     .setIntroducedIn(30708);
```

2021-02-02 14:11 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13827/

2021-02-02 17:29 UTC, jsteemann commented
Tests blue

2021-02-03 10:10 UTC, neunhoef approved these changes
LGTM

2021-02-03 10:11 UTC, merged