Bug fix 3.7/key tests
arangodb/arangodb pull request #13410
Opened 2021-01-20 17:41 UTC by dothebart

backport of https://github.com/arangodb/arangodb/pull/13409

2021-01-27 14:09 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13779/

2021-01-29 13:04 UTC, KVS85 commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13805/

2021-01-29 15:25 UTC, KVS85 commented
> http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13805/

Tests blue except unrelated known failure.

2021-01-29 16:19 UTC, hkernbach commented
Will start review as soon: https://github.com/arangodb/arangodb/pull/13409 is done.

2021-02-04 11:59 UTC, dothebart commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13852/

2021-02-04 15:00 UTC, hkernbach approved these changes
LGTM. Ready to merge after Jenkins run. (If Jenkins is green obviously)

2021-02-04 15:01 UTC, hkernbach requested changes
@dothebart Ah, one thing: Changelog entry is missing.
otherwise LGTM

2021-02-04 18:58 UTC, jsteemann commented
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/13863/

2021-02-04 19:00 UTC, hkernbach approved these changes

2021-02-04 19:01 UTC, jsteemann commented on CHANGELOG
> +* refactor dump & restore testsuites; add autoincrement and padded / uuid tests
```suggestion
* Refactored testsuites for dump & restore, and added tests for autoincrement,
  padded and uuid key generators to it.
```

2021-02-05 00:40 UTC, jsteemann commented
Tests blue

2021-02-05 20:28 UTC, merged