Feature/error messages as string views
arangodb/arangodb pull request #13455
Opened 2021-01-27 14:48 UTC by goedderz

### Scope & Purpose

As the length of error messages (as returned by `TRI_errno_string`) is known at compile time, it makes sense to save and return them as `std::string_view`s instead of `char const*`.

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [X] :fire: Performance improvement
- [X] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [X] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

### Testing & Verification

*(Please pick either of the following options)*

- [X] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [X] This change is already covered by existing tests, such as *scripts/unittest*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

2021-01-27 14:48 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13782/

2021-01-28 09:34 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13790/

2021-02-01 14:42 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13810/

2021-02-03 07:32 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13836/

2021-02-03 13:33 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13841/

2021-02-04 14:48 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13856/

2021-02-05 06:41 UTC, goedderz commented
![image](https://user-images.githubusercontent.com/11504143/106998890-83886f00-6785-11eb-8f1e-f062dbad058d.png)

2021-02-08 09:27 UTC, maierlars requested changes
`std::string_view::data()` does [not](https://en.cppreference.com/w/cpp/string/basic_string_view/data#Notes) return a null-terminated string.

2021-02-08 09:27 UTC, maierlars commented on arangod/Aql/QueryWarnings.cpp
> +  registerWarning(code, details.data());
I don't know if `registerWarning` expects the string to be null-terminated but `data` from a string is not necessarily null-terminated.

2021-02-08 09:27 UTC, maierlars commented on arangod/Aql/Parser.cpp
>    _query.warnings().registerWarning(errorCode, data);
is `data` null-terminated?

2021-02-08 09:27 UTC, maierlars commented on arangod/Aql/Parser.cpp
> +  return registerParseError(errorCode, format.data(), data, line, column);
`data()` is not null-terminated in general.

2021-02-08 12:58 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13894/

2021-02-10 10:10 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13932/

2021-02-10 13:13 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13936/

2021-02-10 13:24 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13937/

2021-02-10 13:29 UTC, maierlars approved these changes

2021-02-11 07:11 UTC, goedderz commented
![image](https://user-images.githubusercontent.com/11504143/107609986-c0021200-6c40-11eb-8b67-6ce5ed49f02b.png)

2021-02-11 07:16 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13956/

2021-02-11 08:09 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13957/

2021-02-11 08:36 UTC, goedderz commented
http://jenkins.arangodb.biz:8080/job/arangodb-matrix-pr/13958/

2021-02-11 13:13 UTC, maierlars approved these changes

2021-02-11 13:19 UTC, merged