Fixed a count collect bug
arangodb/arangodb pull request #13554
Opened 2021-02-15 13:09 UTC by hkernbach

Backport of: https://github.com/arangodb/arangodb/pull/13553
Please see full details there.

2021-02-15 13:10 UTC, hkernbach commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/13998/

2021-02-15 14:40 UTC, hkernbach commented
![image](https://user-images.githubusercontent.com/1244163/107959830-2c17a980-6fa4-11eb-9142-d9f52b92d844.png)

2021-02-15 15:25 UTC, goedderz requested changes
A minor comment in the tests, otherwise LGTM.

2021-02-15 15:25 UTC, goedderz commented on tests/js/server/aql/aql-queries-optimizer-count.js
> +        collection.save({"someBoolean": false, "someArray": myArray});
Better save all documents in an array, and insert all at once. That saves time when running the tests.

2021-02-15 15:25 UTC, goedderz commented on tests/js/server/aql/aql-queries-optimizer-count.js
> +  };
There should be an assertion that the index is actually used by the `FOR` operation to make sure we test the correct thing. Or alternatively, add an [index hint](https://www.arangodb.com/docs/stable/aql/operations-for.html#indexhint) with `forceIndexHint: true` for the same effect.

2021-02-16 11:01 UTC, hkernbach commented
http://jenkins.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/14001/

2021-02-16 13:03 UTC, goedderz approved these changes

2021-02-17 16:36 UTC, hkernbach commented
jenkins blue.

2021-02-17 16:40 UTC, merged