ZKD Indexes [details missing]
arangodb/arangodb pull request #13650
Opened 2021-03-03 17:19 UTC by maierlars

### Scope & Purpose

Feature development branch for multi dimensional indexes.

- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)

#### Related Information
Still missing.

- [ ] Docs PR:
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification
Still missing.

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

2021-03-11 09:45 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/14312/

2021-05-26 12:07 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/15601/

2021-07-01 10:05 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/16024/

2021-07-05 11:53 UTC, maierlars commented
![image](https://user-images.githubusercontent.com/29692726/124467640-a7c59780-dd87-11eb-8b8e-1ca12031f142.png)

2021-07-21 15:26 UTC, gnusi commented
I fear that the way of how `zkd` index functionality is exposed for the user is a bit counterintuitive. In order to use it, one has to generate a JSON object where fields represent a certain dimensions. That's weird, given json natively supports arrays and vpack representation of an array is by far more efficient than object.

Instead of specifying object fields to be indexed, I suggest the following:
```
{ vec: [ 0, 1, 2, 3, 4 ] }
```
index definition
```
{ 
  fields: [ "vec" ], // only 1 field is allowed
  dimensions: 4 // consider only 4 dimension, e.g. this can raise an error if "vec" contains less than 4 dimensions
}
```
or 
```
{ 
  fields: [ "vec" ], // only 1 field is allowed
  dimensions: [ 0, 1, 3 ] // index only 0, 1 and 3 dimensions
}
```

AQL will look like
```
FOR d IN c
  FILTER d.vec[0] > 0 && d.vec[0] < 42
  FILTER d.vec[1] > 2 && d.vec[1] <= 48
  FILTER d.vec[3] == 8
  RETURN d
```

2021-07-21 15:31 UTC, gnusi commented
I also fear that `zkd` might be a bit misleading for average user, I suggest something like `multidimensional` (but probably it's too long)

2021-07-21 16:11 UTC, gnusi commented
I also suggest we introduce a reasonable upper bound for the number of dimensions

2021-07-22 07:43 UTC, goedderz commented
> I fear that the way of how `zkd` index functionality is exposed for a user is a bit counterintuitive. In order to use it, one has to generate a JSON object where fields represent certain dimensions. That's weird, given json natively supports arrays and vpack representation of an array is by far more efficient than object.
> 
> Instead of specifying object fields to be indexed, I suggest the following:
> 
> ```
> { vec: [ 0, 1, 2, 3, 4 ] }
> ```

That's a sensible idea for this use case, i.e. indexing homogenic dimensions. However, we (also) had in mind more heterogenic dimensions, at least in the future. While we decided to restrain this first version to doubles only, which does limit that somewhat, we have plans how to allow arbitrary json/velocypack values later. In which case allowing one one array to be indexed feels much too restricting.

> I also fear that zkd might be a bit misleading for average user, I suggest something like multidimensional (but probably it's too long)

Agreed, that's why we used multi-dimensional in the documentation. However, as other kinds of multidimensional indexes are available and could be added in the future, we thought it sensible to use the more technical term in the API. And it's also common to specify the implementation of indexes, i.e. btree, hash, rtree, skiplist, etc.

2021-08-12 09:02 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/16576/

2021-08-18 11:31 UTC, gnusi requested changes
There are 2 critical things:
* usage of a rude word for a label
* lack of disclaimer in some files

Other comments are suggestions for performance improvements. 
I'd also add some load tests against at least medium size data set (probably as a part of QA phase).

2021-08-18 11:31 UTC, gnusi commented on arangod/RocksDBEngine/RocksDBZkdIndex.cpp
> +  auto value = RocksDBValue::ZkdIndexValue();
seems to be redundant

2021-08-18 11:31 UTC, gnusi commented on arangod/RocksDBEngine/RocksDBZkdIndex.cpp
> +  auto value = RocksDBValue::ZkdIndexValue();
seems to be redundant

2021-08-20 14:13 UTC, mpoeter approved these changes
LGTM, only some small suggestions.

2021-09-09 13:51 UTC, maierlars commented
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/16971/

2021-09-09 13:52 UTC, goedderz commented on arangod/Zkd/ZkdHelper.cpp
> +  std::vector<CompareResult> result;
Good idea, but I'll create a ticket and do that as a later improvement.

2021-09-09 13:52 UTC, goedderz commented on arangod/RocksDBEngine/RocksDBZkdIndex.cpp
> +  std::vector<zkd::byte_string> v;
Good idea, but I'll create a ticket and do that as a later improvement.

2021-09-10 06:41 UTC, joerg84 approved these changes

2021-09-10 07:00 UTC, merged