Feature 3.7/upgrade js deps 2021 05
arangodb/arangodb pull request #14257
Opened 2021-05-27 10:17 UTC by hkernbach

### Scope & Purpose

Updates following packaged node modules:
- lodash from 4.17.13 -> 4.17.21
- js-yaml from 3.13.0 -> 3.14.1
- underscore from 1.9.1 -> 1.13.1
- raise mocha from 6.1.3 -> 6.2.2

- [x] :hankey: Node modules update
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required

#### Related Information

- [ ] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/ES-867

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.

2021-05-27 10:17 UTC, hkernbach commented
@fceller fyi

2021-06-07 12:37 UTC, pluma commented
Jenkins: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15760/

2021-06-07 13:26 UTC, pluma commented
Build failed because I picked the wrong base branch. Oops.

New build: https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/15764/

2021-06-08 14:07 UTC, pluma commented
Test failure seems to be unrelated (windows only):

```
* Test "recovery_2"
    [FAILED]  tests\js\server\recovery\rangedelete-collection-drop.js

      "test" failed: unable to run recovery test tests\js\server\recovery\rangedelete-collection-drop.js


   Suites failed: 1 Tests Failed: 0
```

2021-06-08 14:08 UTC, pluma approved these changes

2021-06-20 19:45 UTC, KVS85 commented
https://jenkins.arangodb.biz/job/arangodb-ANY-docker-packages/1213/

2021-06-21 12:21 UTC, KVS85 commented
```
Image Digest: sha256:584e525824fd680b22526b4decb03f6dbcfb4a1270474a836e1b0e9e6be30b30
Full Tag: docker.io/arangodb/arangodb-preview:PR14257
Image ID: 1eb1e520e0430d775649b386ac475aaa832f0edc37a341b52e26b6c48b3b4182
Status: fail
Last Eval: 2021-06-21T12:20:19Z
Policy ID: 2c53a13c-1765-11e8-82ef-23527761d060
Final Action: stop
Final Action Reason: policy_evaluation

Gate                   Trigger            Detail                                                                                                                                                                                                                   Status
dockerfile             instruction        Dockerfile directive 'HEALTHCHECK' not found, matching condition 'not_exists' check                                                                                                                                      warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/mocha/node_modules/yargs-parser/package.json (CVE-2020-7608 - https://nvd.nist.gov/vuln/detail/CVE-2020-7608)        warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/netmask/package.json (CVE-2021-29418 - https://nvd.nist.gov/vuln/detail/CVE-2021-29418)                              warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/mocha/node_modules/minimist/package.json (CVE-2020-7598 - https://nvd.nist.gov/vuln/detail/CVE-2020-7598)            warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/xmldom/package.json (CVE-2021-21366 - https://nvd.nist.gov/vuln/detail/CVE-2021-21366)                               warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/highlight.js/package.json (CVE-2020-26237 - https://nvd.nist.gov/vuln/detail/CVE-2020-26237)                         warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - ansi_up (fixed in: 5.0.0)(GHSA-2v5f-23xc-v9qr - https://github.com/advisories/GHSA-2v5f-23xc-v9qr)                                                             warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - highlight.js (fixed in: 10.4.1)(GHSA-7wwv-vh3v-89cq - https://github.com/advisories/GHSA-7wwv-vh3v-89cq)                                                       warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - netmask (fixed in: 2.0.1)(GHSA-pch5-whg9-qr2r - https://github.com/advisories/GHSA-pch5-whg9-qr2r)                                                             warn
vulnerabilities        package            CRITICAL Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/netmask/package.json (CVE-2021-28918 - https://nvd.nist.gov/vuln/detail/CVE-2021-28918)                            stop
vulnerabilities        package            CRITICAL Vulnerability found in non-os package type (npm) - netmask (fixed in: 1.1.0)(GHSA-4c7m-wxvm-r7gc - https://github.com/advisories/GHSA-4c7m-wxvm-r7gc)                                                           stop
```

```
Image Digest: sha256:f3ece184cc4ecbb54fec1d7cd245db5a580b6d62443f506b90a0c767733974af
Full Tag: docker.io/arangodb/enterprise-preview:PR14257
Image ID: ba14e99a55356cd2220c848ff9758ecca9147869d1b1349825abb496de2703b3
Status: fail
Last Eval: 2021-06-21T12:14:15Z
Policy ID: 2c53a13c-1765-11e8-82ef-23527761d060
Final Action: stop
Final Action Reason: policy_evaluation

Gate                   Trigger            Detail                                                                                                                                                                                                                   Status
dockerfile             instruction        Dockerfile directive 'HEALTHCHECK' not found, matching condition 'not_exists' check                                                                                                                                      warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/highlight.js/package.json (CVE-2020-26237 - https://nvd.nist.gov/vuln/detail/CVE-2020-26237)                         warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/mocha/node_modules/minimist/package.json (CVE-2020-7598 - https://nvd.nist.gov/vuln/detail/CVE-2020-7598)            warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/mocha/node_modules/yargs-parser/package.json (CVE-2020-7608 - https://nvd.nist.gov/vuln/detail/CVE-2020-7608)        warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/netmask/package.json (CVE-2021-29418 - https://nvd.nist.gov/vuln/detail/CVE-2021-29418)                              warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/xmldom/package.json (CVE-2021-21366 - https://nvd.nist.gov/vuln/detail/CVE-2021-21366)                               warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - ansi_up (fixed in: 5.0.0)(GHSA-2v5f-23xc-v9qr - https://github.com/advisories/GHSA-2v5f-23xc-v9qr)                                                             warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - highlight.js (fixed in: 10.4.1)(GHSA-7wwv-vh3v-89cq - https://github.com/advisories/GHSA-7wwv-vh3v-89cq)                                                       warn
vulnerabilities        package            MEDIUM Vulnerability found in non-os package type (npm) - netmask (fixed in: 2.0.1)(GHSA-pch5-whg9-qr2r - https://github.com/advisories/GHSA-pch5-whg9-qr2r)                                                             warn
vulnerabilities        package            CRITICAL Vulnerability found in non-os package type (npm) - /usr/share/arangodb3/js/node/node_modules/netmask/package.json (CVE-2021-28918 - https://nvd.nist.gov/vuln/detail/CVE-2021-28918)                            stop
vulnerabilities        package            CRITICAL Vulnerability found in non-os package type (npm) - netmask (fixed in: 1.1.0)(GHSA-4c7m-wxvm-r7gc - https://github.com/advisories/GHSA-4c7m-wxvm-r7gc)                                                           stop
```

2021-06-21 12:22 UTC, KVS85 requested changes
CVEs are still present.

2021-07-29 12:22 UTC, KVS85 commented
https://jenkins.arangodb.biz/job/arangodb-ANY-docker-packages/1336/

2021-07-29 17:22 UTC, KVS85 commented
Superseded by https://github.com/arangodb/arangodb/pull/14502.

2021-07-29 17:22 UTC, closed without merging