Apm 55
arangodb/arangodb pull request #14364
Opened 2021-06-11 16:41 UTC by alexbakharew

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/APM-55
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [x] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-06-15 21:37 UTC, gnusi requested changes
please use `camelCase` and meaningful variable/function names

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +std::string getFunctionName(const AstNode& node) {
no need to return copy

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +
add `TRI_ASSERT` to ensure that the specified `AstNode` is of type `NODE_TYPE_FCALL`

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +                     VPackFunctionParameters const& parameters,
fix indentatino

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +AqlValue calc_function(arangodb::aql::ExpressionContext* expressionContext,
camelCase

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +                     F lambda_func) {
* camelCase 
* use meaningful argument name, e.g. `decayFuncFactory`
* pass by unified reference, i.e. `F&& decayFuncFactory`

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +  auto f = lambda_func(origin, scale, offset, decay);
use meaningful variable name, e.g.
```
auto decayFunc = decayFuncFactory(origin, scale, offset, decay);
```

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +    double sigma_sqr = - (scale * scale) / (2 * std::log(decay));
`const`

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +    return [=](double arg) {
default capture is bad practice, please specify variables that are necessary for evaluation

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +  auto gauss_decay_f = [](const double origin, const double scale, const double offset, const double decay) {
`gaussDecayFactory`

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +  auto exp_decay_f = [](const double origin, const double scale, const double offset, const double decay) {
expDecayFactory

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +  auto linear_decay_f = [](const double origin, const double scale, const double offset, const double decay) {
linearDecayFactory

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +AqlValue calc_function(arangodb::aql::ExpressionContext* expressionContext,
* camelCase
* use meaningful function name, e.g. `decayFuncImpl`
* move to annonymous namespace

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +      for (VPackSlice curr_arg : VPackArrayIterator(slice)) {
camelCase

2021-06-15 21:37 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +  auto exp_decay_f = [](const double origin, const double scale, const double offset, const double decay) {
80 symbols

2021-06-15 21:37 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +SmallVector<AqlValue> create_arg_vec(const VPackSlice slice) {
camelCase

2021-06-15 21:37 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +void expect_eq_slices(const VPackSlice actual_slice, const VPackSlice expected_slice) {
camelCase

2021-06-15 21:37 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +AqlValue evaluateDecayFunction(const SmallVector<AqlValue>& params, const FunctionType& type ) {
I suggest you pass `Function` instead of `FunctionType`

2021-06-15 21:37 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +  auto const expected_json = VPackParser::fromJson(expected);
camelCase

2021-06-16 11:39 UTC, gnusi requested changes

2021-06-16 11:39 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +  return;
redundant

2021-06-16 11:39 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +enum class FunctionType {
don't need anymore

2021-06-16 11:39 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +                         F&& decayFunction,
`Function const& decayFunction`

2021-06-16 11:39 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +                               F&& decayFunction,
we don't need a template
`Function const& decayFunction`

2021-06-16 11:50 UTC, Dronplane commented on arangod/Aql/Functions.cpp
> +    return AqlValue(builder.slice());
Suggest to use AqlValue ctor from buffer to avoid unnecessary copying 
```suggestion
    return AqlValue(std::move(*builder. steal()));
```

2021-06-16 12:48 UTC, Dronplane requested changes
Also please add some js tests, at least one per function to verify behaviour in server as a whole

2021-06-17 10:28 UTC, gnusi approved these changes

2021-06-17 10:58 UTC, Simran-B commented
Should the AQL functions be renamed to `DECAY_GAUSS`, `DECAY_EXP` and `DECAY_LINEAR`?

2021-06-17 11:15 UTC, Dronplane approved these changes
LGTM

2021-06-17 12:37 UTC, alexbakharew commented
Functions are renamed

2021-06-17 14:13 UTC, merged