Search 161 3.7
arangodb/arangodb pull request #14444
Opened 2021-07-01 16:14 UTC by alexbakharew

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-07-01 16:28 UTC, gnusi approved these changes

2021-07-01 19:36 UTC, gnusi requested changes

2021-07-01 19:36 UTC, gnusi commented on CHANGELOG
> +* Removed redirects from /_admin/cluster* to /_admin/cluster/*. Adjusted
completely unrelated to this PR

2021-07-01 19:36 UTC, gnusi commented on tests/Aql/DecaysFunctionTest.cpp
> +SmallVector<AqlValue> createArgVec(const VPackSlice slice) {
completely unrelated to this PR

2021-07-01 19:36 UTC, gnusi commented on tests/IResearch/IResearchFeature-test.cpp
> +    { "GEO_IN_RANGE", { ".,.,.,.|.,.,.", FunctionType::FILTER } },
completely unrelated to this PR

2021-07-02 10:27 UTC, gnusi approved these changes

2021-07-02 15:28 UTC, KVS85 reviewed
LGTM.

2021-07-02 15:28 UTC, merged