Search-216 - Distance functions in AQL
arangodb/arangodb pull request #14555
Opened 2021-07-28 16:52 UTC by alexbakharew

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [X] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [X] Docs PR: 
- [ ] Enterprise PR:
- [X] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/SEARCH-216
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [X] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-07-28 16:53 UTC, alexbakharew commented
Initial commit. Will be ready for review later

2021-07-28 18:01 UTC, Dronplane requested changes

2021-07-29 08:11 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +    return ::numberValue(numerator / (std::sqrt(lhsSum) * std::sqrt(rhsSum)), true);
this will lead to UB caused by devision by zero in case if `std::sqrt(lhsSum) * std::sqrt(rhsSum)` is equal to 0

2021-07-29 08:11 UTC, gnusi commented on arangod/Aql/Functions.h
> +                              AstNode const&, VPackFunctionParameters const&);
indentation

2021-07-29 08:11 UTC, gnusi commented on arangod/Aql/Functions.h
> +                              AstNode const&, VPackFunctionParameters const&);
indentation

2021-07-29 08:11 UTC, gnusi commented on arangod/Aql/Functions.h
> +                              AstNode const&, VPackFunctionParameters const&);
indentation

2021-07-29 08:11 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +  auto calculateDistance = [&distanceFunc, expressionContext, &node]
```suggestion
auto calculateDistance = [distanceFunc = std::forward<F>(distanceFunc), expressionContext, &node]
```

2021-07-29 08:11 UTC, gnusi commented on arangod/Aql/Functions.cpp
> +        if (dist.isNull(true)) {
```
if (!dist.isNumber()) {
```

2021-07-29 16:10 UTC, Dronplane approved these changes
LGTM

2021-07-29 18:34 UTC, merged