Search-37 - optimizer rules
arangodb/arangodb pull request #14585
Opened 2021-08-03 15:05 UTC by alexbakharew

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [X] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [X] GitHub issue / Jira ticket number: https://arangodb.atlassian.net/browse/SEARCH-37
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [X] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-08-03 15:42 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +    {
Move opening curly brace to the previous line please

2021-08-03 17:11 UTC, alexbakharew commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +          _preCalculated = true;
add geter to this member. So we can test that optimization happened

2021-08-03 17:13 UTC, alexbakharew commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
>        while (_queryResults->numRows() > _resultRowIdx) {
multiple resets without next() will cause missing of the optimization

2021-08-03 17:14 UTC, alexbakharew commented
Add tests for optimization

2021-08-05 09:28 UTC, Dronplane requested changes

2021-08-05 09:28 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +        if(optimize(field)) {
Why we are running optimize again? If we got here - plan was already inspected. We know for sure  if we should optimize or not.

2021-08-05 09:28 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +
If we are in "optimized" mode - why wasting time on node values? We could check here _preCalculated value.

2021-08-05 09:28 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.h
> +#ifdef TEST_F
```suggestion
#ifdef ARANGODB_USE_GOOGLE_TESTS
```
Let's not assume test framework dependent macros is present

2021-08-05 09:28 UTC, Dronplane commented on tests/IResearch/IResearchAqlAnalyzer-test.cpp
> +    ASSERT_FALSE(dynamic_cast<arangodb::iresearch::AqlAnalyzer*>(ptr.get())->isPreCalculated());
Suggest to move that check inside assert_analyzer, so we could check the value right after the reset and not after analyzer was already exhausted

2021-08-05 09:28 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +      if(_optimizedField != field) {
if we call reset twice with the same value - here we will miss the optimization

2021-08-05 09:28 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +      if(_optimizedField != field) {
And we need a test for such case

2021-08-05 10:54 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +  auto deps = node->getDependencies();
let's avoid copying a vector

2021-08-05 10:54 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +    auto deps2 = calcNode->getDependencies();
let's avoid copying a vector

2021-08-06 16:07 UTC, Dronplane commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +    if (calculatedValue.isNull(true) && !_analyzer->_options.keepNull) {
Check here is redundant as `next` alredy handles `keepNull`

2021-08-06 16:10 UTC, gnusi requested changes

2021-08-06 16:10 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +    AqlValue value(field.c_str());
not a c_str()!

2021-08-06 16:10 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +    AqlFunctionsInternalCache cache;
already have this in AqlAnalyzer

2021-08-06 16:10 UTC, gnusi commented on arangod/Aql/FixedVarExpressionContext.h
> +  Variable* _variable;
why not const?

2021-08-06 16:10 UTC, gnusi commented on arangod/Aql/FixedVarExpressionContext.h
> +  Variable* _variable;
value isn't initialized

2021-08-06 16:10 UTC, gnusi commented on arangod/Aql/FixedVarExpressionContext.cpp
> +  return _value;
check if pointers are equal

2021-08-06 16:10 UTC, gnusi commented on arangod/Aql/FixedVarExpressionContext.h
> +  explicit SingleVarExpressionContext(transaction::Methods& trx,
initialize from ctor

2021-08-06 16:10 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +    _nodeToOptimize = dynamic_cast<CalculationNode*>(execNode);
dynamic_cast only in debug, add TRI_ASSERT that execNode is NODE_TYPE_CALCULATION

2021-08-09 21:17 UTC, gnusi requested changes

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +  out = std::move(e->execute(&ctx, mustDestroy));
`std::move` is redundant

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +  return true;
why do you need a return value?

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +  // value not needed since getting it from _bindedNodes
```suggestion
value is not needed since getting it from _bindedNodes
```

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +  return true;
why do you need a return value?

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +bool TryOptimize(AqlAnalyzer* analyzer) {
TryOptimize -> tryOptimize

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +bool OptimizedQuery(AqlAnalyzer* analyzer) {
OptimizedQuery -> resetFromExpression

2021-08-09 21:17 UTC, gnusi commented on arangod/IResearch/IResearchAqlAnalyzer.cpp
> +bool NotOptimizedQuery(AqlAnalyzer* analyzer) {
NotOptimizedQuery -> resetFromQuery

2021-08-10 15:06 UTC, gnusi approved these changes

2021-08-10 15:07 UTC, Dronplane approved these changes
LGTM

2021-08-10 15:09 UTC, merged