Hybrid Smart Graphs: Adds support for clearing Providers
arangodb/arangodb pull request #14594
Opened 2021-08-06 11:49 UTC by hkernbach

### Scope & Purpose

Enumerators are responsible for clearing Providers as well.
Both available Providers (OneSided and TwoSided) got new methods to verify integrity.
ProviderTracer / MockGraphProvider got clear() method due to interface addition.

- [x] :hammer: Refactoring/simplification

#### Backports:

- [x] No backports required

#### Related Information

- [x] Design document: https://arangodb.atlassian.net/secure/RapidBoard.jspa?rapidView=55&modal=detail&selectedIssue=GORDO-1230

### Testing & Verification

- [x] This change is already covered by existing tests, such as *(please describe tests)*.
- [x] This PR adds tests that were used to verify all changes:
  - [x] Added new C++ **ASSERTS**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

2021-08-06 11:50 UTC, hkernbach commented
ASAN run started:
- https://jenkins.arangodb.biz:3456/job/arangodb-ANY-linux-asan/756/

2021-08-06 13:38 UTC, mchacki requested changes
Technical production code looks good to me, this is a good change making everything more secure and avoid Undefined behavior.

However please move the clearProvider methods into private state, as they are unsafe to be called from outside, and never intended to be.

2021-11-10 12:13 UTC, hkernbach commented on arangod/Aql/ExecutionEngine.cpp
> +      // Feature HybridSmartGraphs: Check here.
```suggestion
```

2021-11-11 13:57 UTC, mchacki approved these changes
Technically good, there are some duplicates that can be removed via my inline suggestions.
Mostly comments / whitespace.

2021-11-11 13:57 UTC, mchacki commented on arangod/Aql/QuerySnippet.cpp
> +
```suggestion
```
That is already handled.

2021-11-11 13:57 UTC, mchacki commented on arangod/Aql/QuerySnippet.cpp
> +          // We need one expansion for every non-satellite collection in the Graph (-1 per satellite)
```suggestion
          // We need one expansion for every non-satellite collection in the Graph
```
Non satellite in the comment already.

2021-11-11 13:57 UTC, mchacki commented on arangod/Aql/ShardLocking.cpp
> +        return graphIsUsedAsSatellite || (col->isSatellite() && (pushToSingleServer || graphNode->isSmart())) || (col->isSatellite() && graphNode->isSmart());
```suggestion
        return graphIsUsedAsSatellite || (col->isSatellite() && (pushToSingleServer || graphNode->isSmart())));
```
Covered by the second OR case

2021-11-11 13:57 UTC, mchacki commented on arangod/ClusterEngine/ClusterIndexFactory.cpp
> +      TRI_vocbase_t const& vocbase             ) const override {
```suggestion
      TRI_vocbase_t const& vocbase) const override {
```

2021-11-11 13:57 UTC, mchacki commented on arangod/ClusterEngine/ClusterIndexFactory.cpp
> +        normalized, definition, isCreation, vocbase          );
```suggestion
        normalized, definition, isCreation, vocbase);
```

2021-11-11 13:57 UTC, mchacki commented on arangod/ClusterEngine/ClusterIndexFactory.cpp
> +      definition, normalized, isCreation, vocbase    );
```suggestion
      definition, normalized, isCreation, vocbase);
```

2021-11-11 13:57 UTC, mchacki commented on arangod/Graph/BreadthFirstEnumerator.cpp
> +
```suggestion
```
That code is already there above.

2021-11-11 13:57 UTC, mchacki commented on arangod/Graph/PathEnumerator.cpp
> +
```suggestion
```
Already in the lines above

2021-11-11 13:57 UTC, mchacki commented on arangod/Graph/Providers/ClusterProvider.h
> +    size_t _localSchreierIndex = std::numeric_limits<size_t>::max();  // to be removed later
Is this needed?
I do not see related .cpp code.
maybe this was made obsolete in the original.

2021-11-12 15:49 UTC, merged

2021-11-12 15:50 UTC, mchacki commented
The Red part in Jenkins was arm-build that could not connect to GitHub.
We have seen it green before with non relevant changes.