Feature/hybrid smart graphs documentation
arangodb/arangodb pull request #14590
Opened 2021-08-05 14:52 UTC by hkernbach

### Scope & Purpose

WIP
Documentation for Hybrid (Disjoint) Smart Graphs

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-08-05 14:53 UTC, hkernbach commented
Currently generateSwagger.sh fails.

2021-08-05 14:53 UTC, hkernbach commented
@Simran-B would be awesome if you could help out here.

2021-08-09 13:45 UTC, mchacki requested changes
Minor corrections

2021-08-09 13:45 UTC, mchacki commented on Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_add_http_examples.md
> +Additionally, optional options can be set (Enterprise-Only).
```suggestion
Additionally, collection creation options can be set.
```

2021-08-09 13:45 UTC, mchacki commented on Documentation/DocuBlocks/Rest/Graph/general_graph_vertex_create_http_examples.md
> +Additional options for the vertex to add.
```suggestion
Additional options for the vertex collection to add.
```

2021-08-10 13:25 UTC, hkernbach commented
Examples needs to be generated and then copied over to: https://github.com/arangodb/arangodb/pull/14590

2021-10-12 10:28 UTC, merged