Capture immutable fields during view creation through web UI.
arangodb/arangodb pull request #14726
Opened 2021-09-02 12:34 UTC by adityamukho

### Scope & Purpose

This PR extends the Views web UI, letting it capture View properties that are immutable once created. These include:
1. `primarySort`
2. `storedValues`
3. `primarySortCompression`
4. `writebufferIdle`
5. `writebufferActive`
6. `writebufferSizeMax`

Prior to this fix, any view created through the web UI will necessarily use **default** values for the above properties, and there is no way to change them later.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [x] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-09-03 11:49 UTC, hkernbach approved these changes
Just one very minor thing. LGTM.

2021-09-03 11:49 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
> +    if (style !== undefined) {
```suggestion
    if (style) {
```

2021-09-03 11:49 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
> +    if (style !== undefined) {
```suggestion
    if (style) {
```

2021-09-03 11:49 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
>      if (value !== undefined) {
```suggestion
    if (value) {
```

2021-09-03 12:13 UTC, Dronplane commented
It is not related to this PR but could we include it here also?
at file 
js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersReactView.jsx:174
there is a typo:
"Show In-built Analyzers" should be "Show Built-in Analyzers" to match naming in our docs https://www.arangodb.com/docs/stable/analyzers.html#built-in-analyzers

2021-09-03 12:17 UTC, adityamukho commented
I'm working on a dedicated bugfix PR for analyzers web view. I will include
your suggestion there.

On Fri, 3 Sep, 2021, 17:43 Andrei Lobov, ***@***.***> wrote:

> It is not related to this PR but could we include it here also?
> at file
>
> js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersReactView.jsx:174
> there is a typo:
> "Show In-built Analyzers" should be "Show Built-in Analyzers" to match
> naming in our docs
> https://www.arangodb.com/docs/stable/analyzers.html#built-in-analyzers
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/arangodb/arangodb/pull/14726#issuecomment-912491557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMJKUCNF6N24EETWZQNLA3UAC3WFANCNFSM5DI77QMQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-05 08:52 UTC, hkernbach requested changes
Two places where we do have unused code. Please remove. Otherwise LGTM.

2021-10-05 08:52 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalTable.ejs
> +                                // <i class="moveRowButton moveRowDown disabled fa fa-arrow-circle-down"></i> %>
```suggestion
```

2021-10-05 08:52 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/scss/_modals.scss
> +  }
```suggestion
```

2021-10-05 09:21 UTC, adityamukho commented
> Two places where we do have unused code. Please remove. Otherwise LGTM.

Done!

2021-10-05 09:51 UTC, hkernbach approved these changes

2021-10-05 09:56 UTC, merged