Feature/enterprise license stuff
arangodb/arangodb pull request #14753
Opened 2021-09-09 13:43 UTC by kvahed

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [X] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [X] :book: CHANGELOG entry made

#### Backports:

- [ ] No backports required
- [ ] Backports required for: *(Please specify versions and link PRs)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [X] Docs PR: will announce 
- [X] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [X] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [X] This PR adds tests that were used to verify all changes:
  - [X] Added new C++ **Unit tests**
  - [X] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-09-16 18:01 UTC, jsteemann requested changes

2021-09-16 18:01 UTC, jsteemann commented on arangod/Cluster/ServerState.cpp
> +    _license_readonly.load(std::memory_order_acquire);
This is a behavior change: the previous implementation returned the _previous_ value of the read-only flag, the new implementation returns the new value.
I think it makes sense to restore the old behavior so everything remains fully downwards-compatible.

2021-09-16 18:01 UTC, jsteemann commented on arangod/Cluster/ServerState.h
> +  enum ReadOnlyMode {
I would prefer if we could turn this into an `enum class`. That way we will not have any implicit conversions and only the defined enum values can be used.

2021-09-17 06:02 UTC, kvahed commented on arangod/GeneralServer/GeneralServerFeature.cpp
> +  _handlerFactory->addPrefixHandler("/_admin/license",
It does not. It is inside an ifdef for enterprise builds.

2021-09-17 07:47 UTC, kvahed commented on arangod/Agency/Store.cpp
> +    showHidden |= (query_strs.back().find('.') == 0 || (query_strs.back().find("/.") != std::string::npos));
this is ok. we need to be able to spot ".agency" as well as "/.agency".

2021-09-17 17:50 UTC, jsteemann commented on js/client/modules/@arangodb/testsuites/license.js
> +  // turn off ldap tests by default.
```suggestion
  // turn off license tests by default.
```

2021-09-17 17:51 UTC, jsteemann approved these changes

2021-09-27 15:11 UTC, jsteemann approved these changes

2021-09-28 12:02 UTC, merged