Fix race in RocksDBThrottle
arangodb/arangodb pull request #14856
Opened 2021-10-04 12:50 UTC by jsteemann

### Scope & Purpose

* Fix race in RocksDB throttle listener, when it was getting started lazily during server shutdown.

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [x] :book: CHANGELOG entry made

#### Backports:

- [x] Backports required for: *3.7*

### Testing & Verification

- [x] This change is a trivial rework / code cleanup without any test coverage.
- [x] The behavior in this PR was *manually tested*

2021-10-04 17:20 UTC, mpoeter requested changes

2021-10-05 08:05 UTC, jsteemann commented on arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
> +    TRI_ASSERT(state == ThrottleState::Starting);
I agree, the assert is wrong here, and I will remove it. Good catch!

2021-10-05 10:03 UTC, mpoeter approved these changes

2021-10-05 11:13 UTC, KVS85 approved these changes
LGTM.

2021-10-05 13:11 UTC, merged