Feature/move leader
arangodb/arangodb pull request #15079
Opened 2021-11-09 18:52 UTC by ajurdak

### Scope & Purpose

Allow to move a server to its current follower.

- [x] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [x] :book: CHANGELOG entry made

### Testing & Verification

*(Please pick either of the following options)*

- [x] The behavior in this PR was *manually tested*

2021-11-11 15:25 UTC, hkernbach commented on CHANGELOG
> +
```suggestion
* In the shards overview the list of servers to move the leader shard to, now
  also contains the current followers. This means that from now on also active
  follower servers can be nominated as the leading server for that specific
  shard.
```

2021-11-11 15:25 UTC, hkernbach requested changes
Code LGTM. 

Changelog entry was a bit confusing. Tried to improve there. Please check. Feel free to optimize (e.g. language) even further.

2021-11-11 17:59 UTC, hkernbach approved these changes

2021-11-12 15:11 UTC, jsteemann commented on CHANGELOG
> +  shard.
```suggestion
  shard.
  
```

2021-11-12 15:12 UTC, merged