renamed parameters and functions, edited comments
arangodb/arangodb pull request #15108
Opened 2021-11-12 14:35 UTC by romanatarango

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] Backport for 3.9: *(Please link PR)*
- [ ] Backport for 3.8: *(Please link PR)*
- [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-11-12 16:22 UTC, hkernbach commented
![image](https://user-images.githubusercontent.com/1244163/141499678-f08df86f-049d-4215-a194-263df8af29e2.png)
@romanatarango fyi: After the refactor is done, we need to remove all Methods which are being unused then from our SmartEdge Classes.

2021-11-26 10:52 UTC, hkernbach requested changes
using keyGenerator is not allowed to be const. As @mchacki told me once, that the key generator uses / increments ticks to be able to create unique keys.

2021-11-26 10:52 UTC, hkernbach commented on arangod/VocBase/LogicalCollection.cpp
> +std::string LogicalCollection::createKeyBetweenSmartAndSat(VPackSlice) const {
```suggestion
std::string LogicalCollection::createKeyBetweenSmartAndSat(VPackSlice) {
```

2021-11-26 10:52 UTC, hkernbach commented on arangod/VocBase/LogicalCollection.cpp
> +std::string LogicalCollection::createKeyBetweenSmartAndSat(VPackSlice) const {
using keyGenerator is not allowed to be const. As @mchacki told me once, that the key generator uses / increments ticks to be able to create unique keys.

2021-11-26 10:52 UTC, hkernbach commented on arangod/VocBase/LogicalCollection.h
> +  std::string createKeyBetweenSmartAndSat(arangodb::velocypack::Slice edgeSlice) const;
```suggestion
  std::string createKeyBetweenSmartAndSat(arangodb::velocypack::Slice edgeSlice);
```

2021-11-26 10:52 UTC, hkernbach commented on arangod/VocBase/LogicalCollection.h
> +  std::string createKeyBetweenSmartAndSat(arangodb::velocypack::Slice edgeSlice) const;
using keyGenerator is not allowed to be const. As @mchacki told me once, that the key generator uses / increments ticks to be able to create unique keys.

2021-12-04 13:34 UTC, mpoeter approved these changes

2022-03-21 15:58 UTC, closed without merging