optimized description of satelliteCollections entry during graph crea…
arangodb/arangodb pull request #15141
Opened 2021-11-17 12:46 UTC by hkernbach

3.9 Port of: https://github.com/arangodb/arangodb/pull/15140
Please see description there

2021-11-17 22:41 UTC, Simran-B requested changes

2021-11-17 22:41 UTC, Simran-B commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
> +              'Those defined collections will be created as satellite collections, and therefore will be replicated to all database servers.',
```suggestion
              'Those defined collections will be created as SatelliteCollections, and therefore will be replicated to all DB-Servers.',
```

2021-11-17 22:41 UTC, Simran-B commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
> +            'Those defined collections will be created as satellite collections, and therefore will be replicated to all database servers.',
```suggestion
            'Those defined collections will be created as SatelliteCollections, and therefore will be replicated to all DB-Servers.',
```

2021-11-18 21:42 UTC, ajurdak approved these changes
LGTM

2021-11-24 15:30 UTC, KVS85 approved these changes
LGTM.

2021-11-24 15:32 UTC, merged