Fix data race
arangodb/arangodb pull request #15362
Opened 2021-12-15 17:06 UTC by MBkkt

### Scope & Purpose

*(Please describe the changes in this PR for reviewers - **mandatory**)*

- [ ] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] Backport for 3.9: *(Please link PR)*
- [ ] Backport for 3.8: *(Please link PR)*
- [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-12-15 17:13 UTC, Dronplane approved these changes
LGTM

2021-12-16 10:47 UTC, mpoeter approved these changes

2021-12-16 13:18 UTC, gnusi requested changes

2021-12-16 13:18 UTC, gnusi commented on arangod/IResearch/IResearchLink.cpp
> +  READ_LOCKER(metaLock, _dataStore._mutex);  // '_meta' can be asynchronously modified
I suggest we simplify this a bit
```
  decltype(_dataStore._meta._cleanupIntervalStep) cleanupIntervalStep{};
  decltype(_dataStore._meta._commitIntervalMsec) commitIntervalMsec{};
  {
    READ_LOCKER(metaLock, _dataStore._mutex); // '_meta' can be asynchronously modified
    cleanupIntervalStep = _dataStore._meta._cleanupIntervalStep;
    commitIntervalMsec = _dataStore._meta._cleanupIntervalStep;
  }

  // If auto commit is disabled, we want to manually trigger the cleanup for the consistent API
  if (_commitIntervalMsec == 0 && cleanupIntervalStep != 0 && ++_cleanupIntervalCount >= cleanupIntervalStep) {
    _cleanupIntervalCount = 0;
    (void)cleanupUnsafe();
  } 
```

2021-12-16 17:26 UTC, gnusi approved these changes

2021-12-16 17:26 UTC, merged