BTS-693 fix for limit with materializer
arangodb/arangodb pull request #15401
Opened 2021-12-22 15:10 UTC by Dronplane

### Scope & Purpose

Fix call limits for the constrained sort node by placing additional limit node right after the constrained sort (or moving existing node if possible)

- [x] :hankey: Bugfix (requires CHANGELOG entry)
- [ ] :pizza: New feature (requires CHANGELOG entry, feature documentation and release notes)
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification
- [ ] :book: CHANGELOG entry made

#### Backports:

- [ ] Backport for 3.9: *(Please link PR)*
- [ ] Backport for 3.8: *(Please link PR)*
- [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket number:
- [ ] Design document: 

### Testing & Verification

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.
- [ ] The behavior in this PR was *manually tested*
- [ ] This change is already covered by existing tests, such as *(please describe tests)*.
- [ ] This PR adds tests that were used to verify all changes:
  - [ ] Added new C++ **Unit tests**
  - [ ] Added new **integration tests** (e.g. in shell_server / shell_server_aql)
  - [ ] Added new **resilience tests** (only if the feature is impacted by failovers)
- [ ] There are tests in an external testing repository:
- [ ] I ensured this code runs with ASan / TSan or other static verification tools

Link to Jenkins PR run:

### Documentation

> All new features should be accompanied by corresponding documentation. 
> Bugs and features should furthermore be documented in the CHANGELOG so that
> support, end users, and other developers have a concise overview. 

- [ ] Added entry to *Release Notes* 
- [ ] Added a new section in the *Manual* 
- [ ] Added a new section in the *HTTP API* 
- [ ] Added *Swagger examples* for the HTTP API  
- [ ] Updated license information in *LICENSES-OTHER-COMPONENTS.md* for 3rd party libraries

### External contributors / CLA Note 

Please note that for legal reasons we require you to sign the [Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

2021-12-23 15:39 UTC, gnusi approved these changes
LGTM

2021-12-23 15:45 UTC, mchacki requested changes
Technical solution looks very good :+1:

Requested Change: We need some tests to back this up, the issue triggered here is rather tricky so needs a good coverage.

2021-12-23 15:45 UTC, mchacki commented on arangod/Aql/OptimizerRule.h
> +  static_assert(moveCalculationsUpRule < applySortLimitRule,
Very good :+1:

2021-12-28 16:07 UTC, gnusi approved these changes

2021-12-28 16:07 UTC, gnusi commented on arangod/Aql/ExecutionEngine.cpp
> +  explicit LimitFullCountChecker() noexcept {}
```suggestion
LimitFullCountChecker() = default;
```

2021-12-29 10:08 UTC, mchacki approved these changes
LGTM

2021-12-29 10:08 UTC, mchacki commented on arangod/Aql/ExecutionEngine.cpp
> +struct LimitFullCountChecker final
This looks very good, thanks for implementing :+1:

2021-12-29 10:08 UTC, mchacki commented on tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
> +      testRegressionBts611() {
Like this test 👍

2021-12-29 10:11 UTC, merged