BTS-735 Fix potential deadlocks
arangodb/arangodb pull request #15533
Opened 2022-01-14 20:21 UTC by MBkkt

### Scope & Purpose

*(Please describe the changes in this PR for reviewers, motivation, rationale - **mandatory**)*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-01-14 20:23 UTC, MBkkt commented on arangod/IResearch/IResearchLink.cpp
> -    if (!_asyncSelf.get()) {
bug here

2022-01-14 20:24 UTC, MBkkt commented on arangod/IResearch/IResearchLink.cpp
> -  if (!_asyncSelf) {
Bug here

2022-01-14 20:25 UTC, MBkkt commented on arangod/IResearch/IResearchLink.cpp
> -  if (!_asyncSelf.get()) {
Bug here

2022-01-14 20:26 UTC, MBkkt commented on arangod/IResearch/IResearchView.h
> +  // as PhysicalCollection::_indexes (IResearchLink::insert)
Main issue

2022-01-14 20:27 UTC, MBkkt commented on arangod/IResearch/IResearchView.h
> +  // as PhysicalCollection::_indexes (IResearchLink::insert)
Main issue

2022-01-14 20:29 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> +          impl->_collections.try_emplace(cid, impl->_links.end());
_collections same as old _links
_links only for collection link that is not null

2022-01-14 20:30 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> +  // TODO Maybe we want sync all and skip errors, now we stop on first error?
Check this plz

2022-01-14 20:31 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> +    for (auto& entry : _links) {
your attention

2022-01-14 20:32 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> -    auto links = _links;
strange

2022-01-15 09:33 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> +      }
We can check `collections->containes` before `->lock()` if we would store `collection id` in `entry`.
But I think `shared_lock` is not critical and this code ok

2022-01-17 10:41 UTC, mpoeter approved these changes

2022-01-18 13:27 UTC, mpoeter requested changes
If this PR fixes some of the issues currently listed in tsan_suppression, then these should be removed.

2022-01-18 13:29 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> -    return _collections.size() == count;
Don't know why we want equal but not greater subset

2022-01-18 14:53 UTC, MBkkt commented on arangod/IResearch/IResearchLink.h
> +    AsyncValue<IResearchLink>::Value _lock;
NIT
use `LinkLock`

2022-01-18 14:55 UTC, MBkkt commented on arangod/IResearch/IResearchView.h
> +  mutable arangodb::iresearch::kludge::read_write_mutex _mutex;
NIT
don't need to write `arangodb::iresearch::`

2022-01-18 15:24 UTC, MBkkt commented on arangod/IResearch/IResearchView.cpp
> +             it->second->second->empty()) {  // TODO REPLACE
remove todo

2022-01-18 15:35 UTC, MBkkt commented
> If this PR fixes some of the issues currently listed in tsan_suppression, then these should be removed.
@mpoeter  You don't merge your PR in devel yet

2022-01-20 13:21 UTC, MBkkt commented
https://github.com/arangodb/arangodb/pull/15576

2022-01-20 13:21 UTC, closed without merging