Use C++20 likely/unlikely instead of macro
arangodb/arangodb pull request #15621
Opened 2022-01-27 15:04 UTC by MBkkt

### Scope & Purpose

Use C++20 likely/unlikely standard attributes instead of compiler-dependent ADB_ macros

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-01-27 15:19 UTC, Dronplane requested changes
If we want to switch  - we need to remove ADB_LIKELY/UNLIKELY macros definition from system-compiler.h or it will be hard to force usage of new style. At least I can't find this change in the PR

2022-01-27 15:19 UTC, Dronplane commented on 3rdParty/fuerte/src/debugging.h
> +    if (!(expr)) [[likely]] {                                              \
```suggestion
    if (!(expr)) [[unlikely]] {                                              \
```

2022-01-27 15:39 UTC, MBkkt commented
@Dronplane 
> If we want to switch - we need to remove ADB_LIKELY/UNLIKELY macros definition from system-compiler.h or it will be hard to force usage of new style. At least I can't find this change in the PR

Ok. See deprecate commit

2022-01-27 15:41 UTC, MBkkt commented on arangod/Replication/DatabaseInitialSyncer.cpp
> -  if (!ADB_LIKELY(marker.isObject())) {
:(

2022-01-27 15:44 UTC, MBkkt commented on lib/Basics/ResourceUsage.cpp
> +    if (_limit > 0 && current > _limit) [[unlikely]] {
changes

2022-01-27 16:53 UTC, jsteemann commented on arangod/Aql/AqlItemMatrix.cpp
> +  return ADB_LIKELY_DEPRECATED(_matrix != nullptr) &&
Instead of using the deprecated macro, can we remove the annotation here completely? Sounds better than supporting the deprecated macro.

2022-01-27 16:53 UTC, jsteemann commented on arangod/Aql/AqlItemMatrix.cpp
> +  return ADB_LIKELY_DEPRECATED(a._matrix == b._matrix) &&
same

2022-01-27 16:54 UTC, jsteemann commented on arangod/Aql/IResearchViewExecutor.cpp
> +    if ((impl.writeRow(ctx, bufferEntry))) [[likely]] {
```suggestion
    if (impl.writeRow(ctx, bufferEntry)) [[likely]] {
```

2022-01-27 16:54 UTC, jsteemann commented on arangod/Aql/IResearchViewExecutor.cpp
> +  if ((documentId.isSet())) [[likely]] {
```suggestion
  if (documentId.isSet()) [[likely]] {
```

2022-01-27 16:57 UTC, jsteemann commented on arangod/GeneralServer/H2CommTask.cpp
> +    while (ADB_UNLIKELY_DEPRECATED(!_responses.push(tmp) && --retries > 0)) {
Let's remove the deprecated macro. Not repeating this for the following occurrences.

2022-01-27 17:01 UTC, jsteemann commented on arangod/RocksDBEngine/RocksDBComparator.cpp
> +  if (lhs.size() == objectIDLength || rhs.size() == objectIDLength) [[likely]] {
```suggestion
  if (lhs.size() == objectIDLength || rhs.size() == objectIDLength) [[unlikely]] {
```

2022-01-27 17:03 UTC, jsteemann commented on lib/Basics/ResourceUsage.cpp
> +    if (_limit > 0 && current > _limit) [[unlikely]] {
Changing it here should be fine.

2022-03-11 15:51 UTC, MBkkt commented
AppleClang support likely/unlike attributes from 13 version.
![[https://en.cppreference.com/w/cpp/compiler_support](compiler_support)](https://user-images.githubusercontent.com/32071355/157901262-cbbeacb1-732e-4408-82b3-52526c47b6e6.png)

But we use 12 now, so I close PR

2022-03-11 15:51 UTC, closed without merging