Feature/views web UI
arangodb/arangodb pull request #16419
Opened 2022-06-17 09:49 UTC by adityamukho

### Scope & Purpose

This PR implements fixes for the Aardvark UI for ArangoSearch Views.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [x] Design document: https://docs.google.com/document/d/13pm4ckpf-qXpeabZ8kFDamZV3c-EYC9LJMXiUErjOqg/edit#

2022-06-29 17:12 UTC, ajurdak approved these changes
Nice work! LGTM.

2022-06-30 09:32 UTC, nikhil-varma reviewed
Reviewed it. Just a few questions/suggestions. We can consider these for as improvements for future PRs 🙂

2022-06-30 09:35 UTC, nikhil-varma commented on js/apps/system/_admin/aardvark/APP/react/src/views/views/Components/LinkList.tsx
> +            ? <SaveButton view={formState} oldName={name} setChanged={setChanged}/>
Same wherever similar logic is being followed

2022-06-30 09:40 UTC, adityamukho commented on js/apps/system/_admin/aardvark/APP/react/src/views/views/Components/LinkList.tsx
> +            ? <SaveButton view={formState} oldName={name} setChanged={setChanged}/>
If JSX is happy, I don't mind switching to the shorter style.

2022-06-30 09:41 UTC, adityamukho commented on js/apps/system/_admin/aardvark/APP/react/src/views/views/Components/ViewLinkLayout.tsx
> +const ViewLinkLayout = ({ fragments = [], children }: ViewLinkLayoutProps) =>
Good point!

2022-06-30 09:49 UTC, nikhil-varma commented on js/apps/system/_admin/aardvark/APP/react/src/views/views/Components/LinkList.tsx
> +            ? <SaveButton view={formState} oldName={name} setChanged={setChanged}/>
Yep it'll work

2022-06-30 12:05 UTC, hkernbach approved these changes
Huge PR! LGTM, as far as I can tell (without knowing all the new react based components and mechanisms). Only marked a few sections with old comments, which can be removed.

2022-07-01 11:40 UTC, KVS85 requested changes
Need CHANGELOG entry for such a big change.

2022-07-01 15:42 UTC, KVS85 approved these changes
LGTM.

2022-07-01 15:56 UTC, merged