[PREGEL] APM-538 Add reporting for storing state observables
arangodb/arangodb pull request #16521
Opened 2022-07-07 22:49 UTC by jvolmer

Add number of vertices measurements.
Additionally, make all measurement variables optional to print them only when they are set.

2022-07-08 07:37 UTC, romanatarango requested changes

2022-07-08 07:37 UTC, romanatarango commented on arangod/Pregel/GraphStore.cpp
> +    ++(*_observables.edgesLoaded);
This should be done only when we are sure that the edge is really added and no error occurs.

2022-07-08 07:37 UTC, romanatarango commented on arangod/Pregel/GraphStore.cpp
> +    if (numDocs % 1000 == 0) {
We may want to change the constant later. I suggest to give it a name and define it where all other such constants are kept (like in `Utils.h/cpp`).

2022-07-08 07:37 UTC, romanatarango commented on arangod/Pregel/Status/Status.h
> +auto add(std::optional<T> a, std::optional<T> b) -> std::optional<T> {
Why not const reference? If in later use `a` and/or `b` are larger than just numbers, it would make no sense to copy them.

2022-07-08 12:01 UTC, jvolmer commented
TODO merge parent first

2022-07-12 08:58 UTC, markuspf requested changes
I am not sure the `std::optional<std::atomic<std::size_t>>` construct is correct.

2022-07-12 08:58 UTC, markuspf commented on arangod/Pregel/GraphStore.cpp
> +  _observables.memoryBytesUsed = 0;
is this only executed once per worker?

2022-07-12 08:58 UTC, markuspf commented on arangod/Pregel/Status/Status.h
> +  std::optional<std::atomic<std::size_t>> verticesStored;
Is this correct? Imagine one thread observing that `verticesLoaded` is `std::nullopt` and deciding to emplace `std::atomic<std::size_t>{5}` in there; another thread also observes `std::nullopt` and puts `std::atomic<std::size_t>{15}` into `verticesLoaded`, when you actually want `20` as the total you will have either `5` or `15` depending on who is faster.

2022-07-13 16:23 UTC, markuspf approved these changes
Looks good to me.

2022-07-13 16:45 UTC, markuspf approved these changes
LGTM

2022-07-13 17:45 UTC, jvolmer commented
Successful run for all except Windows: https://jenkins01.arangodb.biz/job/arangodb-matrix-pr/22502/

2022-07-14 13:11 UTC, merged