Add Search -- new type of views that is alias for InvertedIndex
arangodb/arangodb pull request #16548
Opened 2022-07-14 13:56 UTC by MBkkt

### Scope & Purpose

TODO

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-07-14 21:04 UTC, gnusi requested changes

2022-07-14 21:18 UTC, MBkkt commented on lib/Basics/UnshackledMutex.cpp
> -void UnshackledMutex::lock() noexcept {
Done.
Btw it's my code, early we cannot use std::semaphore because of apple clang

2022-07-18 15:53 UTC, gnusi approved these changes

2022-07-18 20:50 UTC, merged

2022-07-20 09:12 UTC, Dronplane commented on arangod/IResearch/IResearchViewSort.h
> +  void clear() noexcept {
should "clear" and "memory" be virtual? To be on safe side if we will work through base class pointers?

2022-07-20 09:12 UTC, Dronplane commented on arangod/IResearch/Search.cpp
> +    std::this_thread::sleep_for(std::chrono::seconds{10});
Is this sleep intentional? If so, what is the reason behind that? Maybe add a comment why to sleep and why exactly 10s ?