[APM-128] Search offsets
arangodb/arangodb pull request #16581
Opened 2022-07-20 21:25 UTC by gnusi

### Scope & Purpose

Community part of APM-128.

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*
  - [ ] Backport for 3.7: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [x] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-07-22 19:26 UTC, MBkkt approved these changes

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/IResearchFeature.cpp
> +#include "IResearchFeature.h"
```suggestion
#include "IResearch/IResearchFeature.h"
```

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/IResearchOrderFactory.cpp
> +using namespace arangodb;
why don't u put anon namespace to arangodb, that written bellow?

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/SearchFunc.h
> +#pragma once
before include? should be in codestyle?

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/SearchFunc.h
> +  }
is it necessary?
I thought from c++20 enough == + <=>

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/SearchFunc.h
> +      : SearchFunc{var, node}, hash{arangodb::iresearch::hash(node)} {}
equal or hash can throw exception?

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/SearchFuncReplace.cpp
> +              v->name.c_str(), funcName.c_str());
Now we have three option for that 😢, and I think two of them better than this
`THROW_ARANGO_EXCEPTION_MESSAGE` +
1) absl::Substitute("....$0...$1...", v->name, funcName) or absl::StrCat
2) fmt::format, also we have static fmt function for Result, and if I remember correct we can throw result

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/SearchFuncReplace.cpp
> +  arangodb::aql::VarSet usedVars;
```suggestion
  aql::VarSet usedVars;
```

2022-07-22 19:26 UTC, MBkkt commented on arangod/IResearch/SearchFuncReplace.h
> +             hasFunc) {
don't like it, maybe early return?
```C++
  return;
}
const bool hasFunc = ...;
if (!hasFunc/hasFunc)

2022-07-31 12:51 UTC, MBkkt commented on arangod/Aql/IResearchViewExecutor.h
> +  std::array<char, arangodb::iresearch::kSearchDocBufSize> _buf;
```suggestion
  std::array<char, iresearch::kSearchDocBufSize> _buf;
```

2022-07-31 12:51 UTC, MBkkt commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +      irs::make_hashed_ref(database, std::hash<irs::string_ref>())));
Still doesn't work?
Maybe we should remove comment in that case?
Or use another map type

2022-07-31 12:51 UTC, MBkkt commented on arangod/IResearch/IResearchKludge.cpp
> +    }
We discussed and decide didn't do it?
I also think if needed we can achieve it another way (We should have fieldAnalyzerProvider in 'exists', etc)

2022-07-31 12:51 UTC, MBkkt commented on arangod/IResearch/SearchDoc.h
> +  constexpr auto operator<=>(const SearchDoc&) const noexcept = default;
```suggestion
  constexpr auto operator==(SearchDoc const&) const noexcept = default;
  constexpr auto operator<=>(SearchDoc const&) const noexcept = default;
```

Spaceship is enough for comparison but not enough for effective comparison

2022-07-31 12:51 UTC, MBkkt commented on arangod/IResearch/SearchDoc.h
> +    std::memcpy(buf.data() + sizeof _segment, &_doc, sizeof _doc);
I think we should make explicit cast in both case or none

2022-07-31 12:51 UTC, MBkkt commented on arangod/IResearch/SearchDoc.h
> +    if (ADB_LIKELY(kSearchDocBufSize == buf.size())) {
NIT
early return?

2022-07-31 12:51 UTC, MBkkt commented on tests/Aql/RegisterPlanTest.cpp
> +    arangodb::containers::FlatHashMap<VariableId, ExecutionNodeMock*> varSetBy;
```suggestion
    containers::FlatHashMap<VariableId, ExecutionNodeMock*> varSetBy;
```

2022-07-31 12:51 UTC, MBkkt commented on tests/Aql/RegisterPlanTest.cpp
> +    arangodb::containers::FlatHashMap<VariableId, ExecutionNodeMock*> varSetBy;
```suggestion
    containers::FlatHashMap<VariableId, ExecutionNodeMock*> varSetBy;
```

2022-08-03 16:51 UTC, MBkkt requested changes
Also please remove velocypack and rocksdb changes

2022-08-03 16:51 UTC, MBkkt commented on arangod/Aql/IResearchViewNode.h
> +        std::span<aql::CalculationNode*> calcNodes,
```suggestion
        std::span<aql::CalculationNode* const> calcNodes,
```

2022-08-03 16:51 UTC, MBkkt commented on arangod/Aql/IResearchViewNode.cpp
> +    std::span<aql::CalculationNode*> calcNodes,
```suggestion
    std::span<aql::CalculationNode* const> calcNodes,
```

2022-08-03 16:51 UTC, MBkkt commented on arangod/IResearch/IResearchKludge.cpp
> +    }
```suggestion
```

2022-08-03 16:51 UTC, MBkkt commented on arangod/IResearch/IResearchKludge.cpp
> +
```suggestion
```

2022-08-03 19:38 UTC, Dronplane approved these changes
LGTM. Some minor comments.
And do we really need empty arangod/IResearch/IResearchSearchFunc.cpp?

2022-08-03 19:38 UTC, Dronplane commented on arangod/IResearch/SearchDoc.h
> +/// @author Andrey Abramo
```suggestion
/// @author Andrey Abramov
```
:)

2022-08-03 19:38 UTC, Dronplane commented on arangod/Aql/OptimizerRulesFeature.cpp
> +  // apply late materialization for view queries
```suggestion
  // handle offsets for ArangoSearch
```

2022-08-03 19:38 UTC, Dronplane commented on arangod/Aql/OptimizerRule.h
> +    hanldeOffsetInfoFunc,
```suggestion
    handleOffsetInfoFunc,
```
typo

2022-08-04 11:34 UTC, merged