Fix /_admin/cluster/rebalance DocuBlocks
arangodb/arangodb pull request #16666
Opened 2022-07-30 15:29 UTC by KVS85

### Scope & Purpose

Fix /_admin/cluster/rebalance DocuBlocks.

- [x] :hankey: Bugfix

### Checklist

- [x] Backports
  - [x] Backport for 3.9: https://github.com/arangodb/arangodb/pull/16665

#### Related Information

- [x] Jenkins: https://jenkins.arangodb.biz/view/Documentation/job/arangodb-ANY-examples/2244/

2022-08-01 09:35 UTC, Simran-B requested changes
Server replies (`@RESTRETURNCODES`) should be written in present tense.

See the last paragraph of the `@RESTBODYPARAM` about shared structs:
https://github.com/arangodb/docs#restbodyparam
There is already a `1_structs.md` in the Administration folder:
https://github.com/arangodb/arangodb/blob/devel/Documentation/DocuBlocks/Rest/Administration/1_structs.md

2022-08-01 09:35 UTC, Simran-B commented on Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
>  @RESTHEADER{POST /_admin/cluster/rebalance, Compute a set of move shard operations to improve balance.}
The summary seems too long and not end-user focused. A more detailed explanation should go into the `@RESTDESCRIPTION`, which every DocuBlock should have.

The wording leaves it open whether the endpoint actually executes a rebalancing or if it only analysis the situation and proposes how to move shards.

2022-08-01 09:35 UTC, Simran-B commented on Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
> +@RESTDESCRIPTION
The description should not be identical to the summary / brief.

Any reason as to why this was moved down, after the `@RESTBODYPARAM`s?

2022-08-01 09:35 UTC, Simran-B commented on Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
>  other rebalance apis.
How many are there? Should be more concrete.
```suggestion
other rebalance APIs.
```

2022-08-01 09:35 UTC, Simran-B commented on Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
> +List of database names that are excluded from the analysis. (Default [])
```suggestion
List of database names that are excluded from the analysis. (Default: `[]`)
```

2022-08-01 09:35 UTC, Simran-B commented on Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
> +@RESTHEADER{PUT /_admin/cluster/rebalance, Compute a set of move shard operations to improve balance and execute.}
Summary seems too long

2022-08-02 09:06 UTC, KVS85 commented
@Simran-B we need to restore examples generation now. Please, propose your fixes to these DocuBlocks for devel and 3.10 in separate PRs.

2022-08-02 09:07 UTC, maierlars approved these changes

2022-08-02 09:07 UTC, merged