Added validation of unique index fields not to be _key: or :_key
arangodb/arangodb pull request #16758
Opened 2022-08-11 06:03 UTC by cpjulia

### Scope & Purpose

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-08-15 16:58 UTC, jsteemann commented on CHANGELOG
> +  indexes that might have such conditions will remain as they are.
```suggestion
* Disallowed index creation that covers fields in which the field's name starts
  or ends with `:` for single server or cluster when the instance is a
  coordinator or single server. This validation only happens for index creation, 
  so already existing indexes that might use such field names will remain as they are.
```

2022-08-15 16:59 UTC, jsteemann commented on arangod/Indexes/Index.cpp
> +void Index::validateFieldsWithSpecialCase(VPackSlice const& fields) {
Slices are lightweight and only contain a data member, which is a pointer. They can and should be passed by value.
```suggestion
void Index::validateFieldsWithSpecialCase(VPackSlice fields) {
```

2022-08-15 16:59 UTC, jsteemann commented on arangod/Indexes/Index.cpp
> +    if (name.toString().starts_with(":") || name.toString().ends_with(":")) {
Avoid creation of 2 `std::string` temporaries.
```suggestion
    if (name.stringView().starts_with(":") || name.stringView().ends_with(":")) {
```

2022-08-15 17:00 UTC, jsteemann commented on arangod/Indexes/Index.cpp
> +                                     "ending with \":\" are disallowed");
```suggestion
                                     "field names starting or ending with \":\"are disallowed in indexes");
```

2022-08-15 17:00 UTC, jsteemann commented on arangod/Indexes/Index.h
> +  static void validateFieldsWithSpecialCase(velocypack::Slice const& fields);
```suggestion
  /// @brief validates that field names don't start or end with ":"
  static void validateFieldsWithSpecialCase(velocypack::Slice fields);
```

2022-08-15 17:02 UTC, jsteemann commented on arangod/VocBase/Methods/Indexes.cpp
> +  // document has an attribute "value: 123:abc", the shard key would cover
```suggestion
  // document has an attribute {"value": "123:abc"}, the shard key would cover
```

2022-08-15 17:04 UTC, jsteemann commented on tests/js/common/shell/shell-index.js
> +      const indexTypes = ["geo", "fulltext", "persistent", "hash"];
"hash" is an alias type for a "persistent" index. No need to test it separately.
```suggestion
      const indexTypes = ["geo", "fulltext", "persistent"];
```

2022-08-16 15:52 UTC, jsteemann commented on arangod/Indexes/Index.cpp
> +          "field names starting or ending with \":\"are disallowed in indexes");
```suggestion
          "field names starting or ending with \":\" are disallowed in indexes");
```

2022-08-16 17:26 UTC, jsteemann commented on arangod/Indexes/Index.cpp
> +                                     "\":\"are disallowed in indexes");
```suggestion
                                     "\":\" are disallowed in indexes");
```

2022-08-16 17:28 UTC, jsteemann approved these changes
LGTM

2022-08-17 08:27 UTC, Simran-B requested changes

2022-08-17 08:27 UTC, Simran-B commented on arangod/VocBase/Methods/Indexes.cpp
> +  // for indexes that already exist. Example for shardKeys: {"value:"}, if the
```suggestion
  // for indexes that already exist. Example for shardKeys: ["value:"], if the
```

2022-08-18 09:31 UTC, merged