Bug fix/limit size of arangodlogs
arangodb/arangodb pull request #16800
Opened 2022-08-17 10:17 UTC by dothebart

### Scope & Purpose

as seen previously forgetting debug logging in tests leads to unstable CI. Assert this for green tests.

- [x] :hankey: Bugfix

2022-08-17 10:20 UTC, naushniki approved these changes

2022-08-17 17:07 UTC, KVS85 requested changes

2022-08-17 17:07 UTC, KVS85 commented on js/client/modules/@arangodb/testutils/instance.js
> +      return;
I don't think it should be like this. There might be a need to enable TRACE or DEBUG and turn this check off. Moreover, 501kB doesn't sound like a huge log.

2022-08-26 11:39 UTC, KVS85 approved these changes
LGTM.

2022-08-26 11:40 UTC, merged