Bug fix/bts 722 (3.10)
arangodb/arangodb pull request #16894
Opened 2022-08-25 12:05 UTC by hkernbach

Backport of: https://github.com/arangodb/arangodb/pull/16766

NO EE companion.

2022-08-26 12:16 UTC, jsteemann commented on arangod/Graph/PathType.cpp
> +constexpr char const* ShortestPathName = "SHORTEST_PATH";
nit: the constant naming here is inconsistent.
According to our coding conventions, all names should  `k...Name`.
Apart from that, these `char const*`s should be `std::string_views`.
That doesn't need to be fixed in 3.10, but can be addressed in devel only.

2022-08-26 12:17 UTC, jsteemann commented on arangod/Graph/PathType.h
> +    ShortestPath = 3
Nit: according to our naming convention, all enum values should be `k...`.
This can be adjusted in devel only.

2022-08-26 12:18 UTC, jsteemann requested changes
LGTM. Would be nice if the code comments could be addressed in devel later.

2022-08-26 12:18 UTC, jsteemann approved these changes

2022-08-29 06:19 UTC, neunhoef approved these changes
LGTM

2022-08-31 15:03 UTC, KVS85 commented
@joerg84 will communicate https://github.com/arangodb/arangodb/pull/16894#pullrequestreview-1086869622 and https://github.com/arangodb/arangodb/pull/16894#pullrequestreview-1086868382 to @hkernbach.

2022-08-31 15:04 UTC, merged