SEARCH-334 searchField support
arangodb/arangodb pull request #16963
Opened 2022-09-01 16:48 UTC by Dronplane

### Scope & Purpose

Add searchField attribute to mark field as accepting array/values mix as for arangosearch links.

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [x] Tests
  - [ ] **Regression tests**
  - [x] C++ **Unit tests**
  - [x] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR: No enterprise part
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-09-01 17:53 UTC, MBkkt requested changes

2022-09-01 17:53 UTC, MBkkt commented on arangod/IResearch/Search.cpp
> +        it->second.isSearchField != field.second.isSearchField) {
```suggestion
        (it->second.isSearchField != field.second.isSearchField && (prefix == name || prefix,includeAllFields))) {
```

2022-09-01 17:53 UTC, MBkkt commented on arangod/IResearch/Search.cpp
> +
auto sameAnalyzer, sameSearchField = ...

2022-09-01 17:53 UTC, MBkkt commented on arangod/IResearch/Search.cpp
>      }
```cpp
SameCollection = !SkipSameAnalyzer;
if (l.collection == r.collection || l.search != r.search || l.analyzer != r.analyzer) {
  if (prefix.size() == name.size()) {
   if (SameCollection) {
     return error1;
   } else if (l.search != r.search) {
     return error2;
   } else {
     return error3;
   }
  } else if (prefix.includeAllFields) {
   return error;
  }
}
```

2022-09-02 12:34 UTC, gnusi approved these changes

2022-09-02 14:14 UTC, Dronplane commented
tests blue except know failure
 * Test "chaos"
    [FAILED]  tests\js\client\chaos\test-module-chaos-load-cluster.js__with_IntermediateCommits_with_FailurePoints_with_Delays_with_StreamingTransactions_with_Truncate_with_VaryingOverwriteMode

      "testWorkInParallel_with_IntermediateCommits_with_FailurePoints_with_Delays_with_StreamingTransactions_with_Truncate_with_VaryingOverwriteMode" failed: Error: at assertion #603: Shards were not getting in sync in time, giving up!: (false) does not evaluate to true

2022-09-02 14:14 UTC, merged