upgrade RocksDB version to 7.7
arangodb/arangodb pull request #17150
Opened 2022-09-21 10:12 UTC by jsteemann

### Scope & Purpose

Upgrade RocksDB to 7.7 in devel

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [x] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-11-22 08:08 UTC, Simran-B requested changes

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +                  "enable blob files for documents column family",
```suggestion
                  "Enable blob files for the documents column family.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +          "enable caching of blobs in block cache for documents column family",
```suggestion
          "Enable caching of blobs in the block cache for the documents "
          "column family.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +          "family (in bytes, requires `--rocks.enable-blob-files`)",
```suggestion
          "The minimum size threshold for storing blobs in the documents "
          "column family (in bytes). Requires `--rocks.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +                  "(in bytes, requires `--rocksdb.enable-blob-files`)",
```suggestion
                  "The size limit for blob files in the documents column "
                  "family (in bytes). Requires `--rocksdb.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +                  "column family (requires `--rocksdb.enable-blob-files`)",
```suggestion
                  "The level from which on to use blob files in the documents "
                  "column family. Requires `--rocksdb.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +          "family (requires `--rocksdb.enable-blob-files`)",
```suggestion
          "The age cutoff for garbage collecting blobs in the documents "
          "column family. Requires `--rocksdb.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +                  "`--rocksdb.enable-blob-files`)",
```suggestion
                  "The garbage threshold for scheduling targeted compactions "
                  "for the oldest blob files in the documents column family. "
                  "Requires `--rocksdb.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +                  "column family (requires `--rocksdb.enable-blob-files`)",
```suggestion
                  "The compression algorithm to use for blobs within the "
                  "documents column family. "
                  "Requires `--rocksdb.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +          "column family (requires `--rocksdb.enable-blob-files`)",
```suggestion
          "Enable blob garbage compaction during compaction in the "
          "documents column family. Requires `--rocksdb.enable-blob-files`.",
```

2022-11-22 08:08 UTC, Simran-B commented on arangod/RocksDBEngine/RocksDBOptionFeature.cpp
> +                  "prepopulate blob cache on flushes",
```suggestion
                  "Prepopulate the blob cache on flushes.",
```

2024-03-01 11:18 UTC, jsteemann commented on CMakeLists.txt
> -add_definitions("-DROCKSDB_SUPPORT_THREAD_LOCAL")
note: the new version of RocksDB does not react to a define `ROCKSDB_SUPPORT_THREAD_LOCAL` anymore, so the line can be removed.

2024-03-01 11:28 UTC, jsteemann commented on CMakeLists.txt
> -add_definitions("-DNROCKSDB_THREAD_STATUS")
note: the new version of RocksDB still checks for a define `NROCKSDB_THREAD_STATUS`, but if it is set, then it does not link anymore. So it seems that the option is now unsupported and we shouldn't set it anymore. Thus removed it here.

2024-03-01 18:38 UTC, jsteemann commented on arangod/RocksDBEngine/RocksDBRateLimiterThread.cpp
> +          LOG_TOPIC("37e36", INFO, Logger::ENGINES)
Note to self: log level needs to be lowered to `DEBUG` here. The `INFO` is currently only there to have enough output during some performance test runs.

2024-07-22 08:32 UTC, closed without merging