[BTS-969]
arangodb/arangodb pull request #17154
Opened 2022-09-21 12:39 UTC by cpjulia

### Scope & Purpose

This PR is a solution for https://arangodb.atlassian.net/browse/BTS-969, it adds a restriction to http request `/_admin/cluster/rebalance` not to consider servers that have health status that is not `"GOOD"` as a possible target for moving shards to. 

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [x] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [x] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports (probably not)

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-969
- [ ] Design document:

2022-09-22 07:57 UTC, maierlars approved these changes

2022-09-22 09:51 UTC, neunhoef requested changes
Other than the tiny thing in the comments, LGTM.

2022-09-22 09:51 UTC, neunhoef commented on arangod/RestHandler/RestAdminClusterHandler.cpp
> +  std::string const leaderPath = "Plan/AsyncReplication/Leader";
This seems superfluous. This key is something for active failover, not needed here.

2022-09-22 09:51 UTC, neunhoef commented on arangod/RestHandler/RestAdminClusterHandler.cpp
> +      AgencyCommHelper::path(healthPath), AgencyCommHelper::path(leaderPath)});
Then `leaderPath` has to be removed here, too.

2022-09-27 15:12 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +let dbServer = null;
Instead of making them global variables, can these be moved inside the `rebalanceSuite`?

2022-09-27 15:13 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +          db["col" + i].insert({"value": j});
Please use batch inserts!

2022-09-27 15:13 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +      }
Not necessary, as the database is going to be dropped anyway.
```suggestion
```

2022-09-27 15:15 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        for (let i = 0; i < dbServers.length; ++i) {
are we expecting `dbServers` to have a minimum length? what if `dbServers` is empty?

2022-09-27 15:16 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +            assertNotEqual(serverHealth, null);
```suggestion
            assertNotNull(result);
            serverHealth = result[dbServer.id].Status;
            assertNotNull(serverHealth);
```

2022-09-27 15:16 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +            if (seconds > 300) {
```suggestion
            if (timeElapsed > 300) {
```

2022-09-27 15:17 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +            }
```suggestion
            assertTrue(timeElapsed < 300, "Server expected status not acquired");
```

2022-09-27 15:17 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +          assertNotEqual(serverHealth, "GOOD");
```suggestion
          assertEqual(serverHealth, "FAILED");
```

2022-09-27 15:18 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +                    return;
```suggestion
```

2022-09-27 15:20 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +          if (moves.length > 0) {
are moves expected here? Right now, there can be 0 moves and the test will pass :thinking:

2022-09-27 15:22 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        assertNotEqual(leaderId, null);
```suggestion
        assertNotNull(leaderId);
```

2022-09-27 15:22 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        if (moves.length > 0) {
Do we expect any moves here? This test will pass with 0 moves...

2022-09-27 15:23 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        assertNotEqual(followerId, null);
```suggestion
        assertNotNull(followerId);
```

2022-09-27 15:23 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        for (const job of moves) {
Are we expecting any moves here?

2022-09-28 13:36 UTC, jsteemann commented on arangod/RestHandler/RestAdminClusterHandler.cpp
> +  }
```suggestion
  for (auto it : velocypack::ObjectIterator(serversHealthInfo)) {
    if (it.value.get("Status").stringView() == "GOOD") {
      activeServers.emplace(it.key.copyString());
    }
  }
```

2022-09-28 13:37 UTC, jsteemann commented on arangod/Cluster/AutoRebalance.h
> +    serversHealthInfo = serversInfo;
```suggestion
      std::unordered_set<std::string> serversInfo) {
    serversHealthInfo = std::move(serversInfo);
```

2022-09-28 13:39 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +          }
Not necessary. We will only have 1000 small objects inside `docs`.
```suggestion
```

2022-09-28 13:41 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        dbServer = dbServers[i];
why it `dbServer` not a local variable here? is it used outside of this test?

2022-09-28 13:47 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +        let serverHealth = null;
If the `suspendExternal` is successfull, the respective DB server is suspended. Fine.
However, if one of the test assertions fail, the DB server may stay suspended for the rest of this test file, and potentially also for all following tests in the `shell_client` suite.
So, if this test suspends a DB server, it must make sure that there are no side effects even if the test fails.
So why not wrap everything that follows the `suspendExternal(...)` into a `try { ... } finally { continueExternal(...); wait until server is GOOD again; }`?

2022-09-28 19:17 UTC, jsteemann commented on tests/js/client/shell/shell-admin-cluster-rebalance.js
> +
No!
This will silence all test assertions!!
```suggestion
```

2022-09-28 19:24 UTC, jsteemann approved these changes
LGTM!

2022-09-29 13:50 UTC, merged