Bug fix 3.10/bts 1070
arangodb/arangodb pull request #17406
Opened 2022-10-21 07:00 UTC by cpjulia

### Scope & Purpose

Backport for https://github.com/arangodb/arangodb/pull/17391.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [x] Tests
  - [ ] **Regression tests**
  - [x] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1070
- [ ] Design document:

2022-10-25 15:44 UTC, jsteemann commented on CHANGELOG
> +
This change seems unrelated to this PR.

2022-10-25 15:44 UTC, jsteemann requested changes
Please adjust the CHANGELOG for this PR. Otherwise LGTM

2022-10-27 18:22 UTC, jsteemann approved these changes
LGTM

2022-11-02 11:14 UTC, maierlars approved these changes

2022-11-02 11:55 UTC, merged