move StaticStrings into a library of its own
arangodb/arangodb pull request #17491
Opened 2022-11-02 16:43 UTC by jsteemann

### Scope & Purpose

Right now this doesn't provide any benefits, but it will allow linking things to arango_static_strings in the future without having to link to everything else in `lib`.

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: -
  - [ ] Backport for 3.9: -
  - [ ] Backport for 3.8: -

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-11-02 17:37 UTC, MBkkt requested changes
I think static strings bad practice.
We should remove this kludge and use directory and namespace like StaticString instead of class with 
inline constexpr constant = "";

Also namespace better because allow to create separate files for different constant

2022-11-02 17:53 UTC, jsteemann commented
> I think static strings bad practice. We should remove this kludge and use directory and namespace like StaticString with inline constexpr constant = ""; instead of class
> 
> Also namespace better because allow to create separate files for different constant

I agree to that using constexpr would be better than using something that is prone to init-order fiascos etc., but that was not the scope of this change.
Re namespaces: yes, why not, but many of these strings here are actually used from a lot of places, including the client-tools (arangosh, arangodump etc.), so we will not be able to move them out of `lib` easily.

2022-11-02 17:54 UTC, markuspf approved these changes
I like this as a way to separate the lib directory into sligthly better units.

as @MBkkt points out, we should move to using constexpr string_views for string constants as well. 

These two moves are not mutually exclusive, though.

2022-11-02 18:00 UTC, MBkkt approved these changes

2022-11-03 07:55 UTC, mchacki approved these changes
LGTM!

2022-11-03 07:55 UTC, merged