Make arangosearch remove faster in recovery and simpler
arangodb/arangodb pull request #17736
Opened 2022-12-05 11:19 UTC by MBkkt

### Scope & Purpose

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-12-05 11:40 UTC, gnusi approved these changes

2022-12-05 11:45 UTC, gnusi requested changes

2022-12-05 12:03 UTC, MBkkt commented on arangod/IResearch/IResearchPrimaryKeyFilter.cpp
>  }
Needs to change code in caller side)

2022-12-08 12:40 UTC, gnusi commented
Closed if favor of #17767

2022-12-08 12:40 UTC, closed without merging