Feature: storedValues can be array of strings
arangodb/arangodb pull request #17794
Opened 2022-12-12 18:30 UTC by MBkkt

### Scope & Purpose

Example: ["a", "b"] instead of [["a"], ["b"]]

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2022-12-12 21:56 UTC, gnusi requested changes

2022-12-12 21:56 UTC, gnusi commented on tests/js/common/aql/aql-view-search-alias-noncluster.js
> -                       storedValues: [["field2"], ["field3"]]});
We still have to test both versions

2022-12-12 22:07 UTC, MBkkt commented on tests/js/common/aql/aql-view-search-alias-noncluster.js
> -                       storedValues: [["field2"], ["field3"]]});
We have above or below

2022-12-29 14:08 UTC, gnusi commented on arangod/IResearch/AqlHelper.cpp
> -    void append(std::string_view const& value) {
.

2022-12-29 14:08 UTC, Dronplane approved these changes
LGTM

2022-12-29 14:48 UTC, MBkkt commented on arangod/IResearch/AqlHelper.cpp
> -    void append(std::string_view const& value) {
Fixed

2022-12-29 14:51 UTC, gnusi approved these changes

2022-12-30 12:00 UTC, merged