BTS-943: testing: move test out of non-existing suite, adjust to new instance methods (#17203)
arangodb/arangodb pull request #17853
Opened 2022-12-21 13:56 UTC by dothebart

Backport of https://github.com/arangodb/arangodb/pull/17203

2022-12-22 09:37 UTC, dothebart commented
it seems that the testresults indicate that we had an API change here between 3.9 -> 3.10

2023-01-09 13:49 UTC, KVS85 approved these changes

2023-01-10 10:06 UTC, KVS85 requested changes
Tests failed.

2023-01-20 16:01 UTC, KVS85 approved these changes

2023-01-20 17:55 UTC, merged