[BTS-266] Turning `--cluster.force-one-shard` on later should not always enable Analyzer optimizations
arangodb/arangodb pull request #17974
Opened 2023-01-18 18:41 UTC by cpjulia

### Scope & Purpose

When starting up a cluster without `--cluster.force-one-shard`, creating a database that might not be single sharded and then restarting the cluster with the startup option `--cluster.force-one-shard` set to true, when the formerly created database has more than one shard, but the flag is set to true, this could lead to arangosearch's analyzers to use optimizations that should not be used if not in a single shard mode. For the optimizations not to happen for the old database created without the `--cluster.force-one-shard` set to true, the verification of the parameter being true as a condition to run optimizations was removed.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [x] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [x] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports 
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

- [ ] Docs PR: 
- [x] Enterprise PR: https://github.com/arangodb/enterprise/pull/1194
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-266
- [ ] Design document:

2023-01-18 20:09 UTC, MBkkt requested changes
Could you add test please?

2023-01-18 20:09 UTC, MBkkt commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +     */
```suggestion
```

2023-01-18 20:09 UTC, MBkkt commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +        (vocbase.isOneShard())) {
```suggestion
        vocbase.isOneShard()) {
```

2023-01-20 04:36 UTC, cpjulia commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +     */
Made in enterprise

2023-01-20 10:02 UTC, MBkkt commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +        return {TRI_ERROR_DEBUG,
Why is this case the error? Both false and both true sounds good?

I understand it's for test but still looks strange

2023-01-20 10:02 UTC, MBkkt commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +                  "force-one-shard true and db is single shard"};
Same question

2023-01-20 13:13 UTC, MBkkt commented on arangod/IResearch/IResearchAnalyzerFeature.cpp
> +        return {TRI_ERROR_DEBUG,
I see, but my question about why do you need fail point for case when forceOneShard == isOneShard

2023-01-22 15:20 UTC, MBkkt commented
Also this PR probably needs backports?

2023-01-23 20:56 UTC, MBkkt approved these changes

2023-01-24 10:00 UTC, mchacki approved these changes
LGTM

2023-01-24 16:50 UTC, Dronplane commented
As a note: this will prevent us from using one-shard optimization for analyzers reading in case of server run with force-one-shard set to true. I'd suggest to make "isOneShard" always return correct value no matter how this "single shard" property was achieved. If that is too much for this PR, let's open a BTS ticket for this, to fix it later on.

2023-01-25 19:47 UTC, jsteemann approved these changes
LGTM

2023-01-26 22:32 UTC, jsteemann commented on js/client/modules/@arangodb/testsuites/server_permissions.js
> +	  global.theInstanceManager = this.instanceManager;
```suggestion
	        global.theInstanceManager = this.instanceManager;
```

2023-01-26 22:32 UTC, jsteemann approved these changes
LGTM

2023-01-26 22:33 UTC, merged