Adjusted default threadCount for dump/restore.
arangodb/arangodb pull request #18130
Opened 2023-02-16 13:53 UTC by joerg84

### Scope & Purpose

*(Please describe the changes in this PR for reviewers, motivation, rationale - **mandatory**)*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-02-17 09:35 UTC, neunhoef requested changes
This would work, but make it unnecessarily complicated.

2023-02-17 09:35 UTC, neunhoef commented on client-tools/Dump/DumpFeature.cpp
> +  _options.threadCount = std::max(uint32_t(_options.threadCount), 4);
A simpler solution would be to remove this code here and simply adjust the default for `Options._threadCount` (from currently 2) to 4 in `client-tools/Dump/DumpFeature.h`.

2023-02-17 09:35 UTC, neunhoef commented on client-tools/Restore/RestoreFeature.cpp
> +  _options.threadCount = std::max(uint32_t(_options.threadCount), 4);
Same here with `client-tools/Restore/RestoreFeature.h` and `struct Options` there.

2023-02-17 09:45 UTC, neunhoef approved these changes
LGTM

2023-02-23 09:48 UTC, jsteemann commented
Seems ok, but will make dump/restore slower in some situations. IMHO there is no "good" default value for the number of threads that does not depend on the deployment's capabilities, so we can as well adjust the default to 4 via this PR.

2023-02-23 09:48 UTC, jsteemann approved these changes
LGTM

2023-02-27 07:43 UTC, neunhoef commented
Since https://arangodb.atlassian.net/browse/BTS-1232 was fixed, this PR is questionable. First, the problem this PR addresses does no longer exist, secondly, this PR could create a new problem, namely that many imports are much slower, since they do not use the full capabilities for parallelism of the client machine, the network and the database itself.
Therefore we should probably give up on it.

2024-02-20 15:00 UTC, closed without merging