[FE-19] Update ArangoDB logo in WebUI
arangodb/arangodb pull request #18226
Opened 2023-03-02 13:19 UTC by pluma4345

### Scope & Purpose

This PR updates the ArangoDB logo in various parts of the WebUI and improves the loginView code somewhat.

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [ ] :fire: Performance improvement
- [x] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] ~~GitHub issue~~ / Jira ticket: FE-19
- [ ] Design document:

2023-03-02 13:28 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js
>          if (self.loginCounter === 0) {
```suggestion
        if (this.loginCounter === 0) {
```

Also needs to be changed now?

2023-03-02 13:29 UTC, hkernbach commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js
> +          : arangoHelper.databaseUrl('/_api/database/user'),
That url build logic could be moved into a helper method as also used here:
- https://github.com/arangodb/arangodb/pull/18226/files#diff-cf85c1e65271ee5d2a8659056f3125557933c993640a3a4a7afee2d96a091ac6R71

2023-03-02 13:31 UTC, hkernbach requested changes
One potential issue where self has been used but not defined anymore. The other very minor. Apart from that "self reference" LGTM.

2023-03-03 12:24 UTC, hkernbach approved these changes

2023-03-06 12:25 UTC, Simran-B approved these changes
LGTM

2023-03-06 13:44 UTC, palashkaria approved these changes
LGTM

2023-03-06 13:48 UTC, hkernbach approved these changes

2023-03-07 21:37 UTC, gnusi requested changes
I don't think iresearch module should be touched by this PR.

2023-03-07 21:37 UTC, Dronplane requested changes
Looks like iresearch module was updated. Is it intentional?

2023-03-07 21:41 UTC, KVS85 requested changes
Please update iresearch submodule according to base branch.

2023-03-07 21:42 UTC, MBkkt requested changes
iresearch submodule shouldn't be update in this pr.

It's probably merge artifact you can revert this change or make reset soft and commit without it

2023-03-08 11:14 UTC, Dronplane approved these changes
LGTM.

2023-03-08 20:47 UTC, KVS85 approved these changes

2023-03-08 20:48 UTC, merged