Support INTO clauses in AQL hashed COLLECT variant
arangodb/arangodb pull request #18254
Opened 2023-03-06 14:36 UTC by jsteemann

### Scope & Purpose

Backport of https://github.com/arangodb/arangodb/pull/18252

* Make the hashed variant of AQL COLLECT support INTO clauses too. Previously only the sorted variant of AQL COLLECT supported INTO clauses.

Helps https://arangodb.atlassian.net/browse/PRESUPP-546

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [x] Backport for 3.10: this PR
  - [ ] Backport for 3.9: -
  - [ ] Backport for 3.8: -

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-03-07 16:18 UTC, mpoeter approved these changes

2023-03-08 09:46 UTC, mchacki requested changes
Production code looks good to me.

But can we have tests for this feature?

All the tests I have seen is that the Optimizer picks the change up and rejects what is incorrect (good)
But there is no "happy path" test, that actually asserts that the behavior of this node is as expected.

2023-03-08 11:22 UTC, mchacki approved these changes
LGTM.
Minor typo in test name, happy to keep it though...

2023-03-08 11:22 UTC, mchacki commented on tests/js/server/aql/aql-optimizer-collect-into.js
> +    testCollectMethodsIntoAndAgreegate : function () {
```suggestion
    testCollectMethodsIntoAndAggregate : function () {
```

2023-03-08 11:22 UTC, mchacki commented on tests/js/server/aql/aql-optimizer-collect-methods.js
> +        docs.push({ group: "test" + (i % 10), value: i, haxe: "test" + i });
Like it :+1:

2023-03-08 15:35 UTC, jsteemann commented
Marked as "DO_NOT_MERGE" because with the PR, execution plans may change in the following way:
* we may have more (extra) execution plans compared to previous 3.10 versions
* the "hash" variant of COLLECT may use more memory than the "sorted" variant
So it is unclear if we want to land this PR in the middle of a stable release. Potentially it is better to introduce the change only in the next version (3.11). 
@Zyqsempai

2023-03-13 10:58 UTC, Zyqsempai requested changes
@jsteemann Let's not backport it to 3.10, considering your concerns and the fact that it could wait till 3.11 release.

2023-03-13 11:46 UTC, jsteemann commented
Closed because feature shouldn't be backported.

2023-03-13 11:46 UTC, closed without merging