[GORDO-1596] Query pregel actor status
arangodb/arangodb pull request #18470
Opened 2023-03-27 21:57 UTC by jvolmer

Adds a new status actor for every conductor.
If a pregel run ist started using actors, the pregel status is provided by the state this actor.

2023-03-28 08:46 UTC, markuspf commented on arangod/Pregel/REST/RestControlPregelHandler.cpp
> +                statusActor.id);
In an ideal world this would be a function `getStatusActorFor(executionNumber)`; I realise this is only used in this one place and I am nitpicking.

2023-03-28 08:47 UTC, markuspf commented on arangod/Pregel/StatusActor.h
> +};
One day we might want to figure out how to default handlers like this ;)

2023-03-28 08:48 UTC, markuspf requested changes
Small comment about serialising the error message we should get from the inspector.

2023-03-28 12:47 UTC, markuspf approved these changes
LGTMN

2023-03-30 12:39 UTC, jvolmer reviewed
nice

2023-03-31 08:34 UTC, merged