Feature/license feature v2
arangodb/arangodb pull request #18518
Opened 2023-03-30 15:02 UTC by kvahed

### Scope & Purpose

*Expand license feature for resources and components*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-04-04 09:33 UTC, maierlars requested changes
`NumberOfCoresCache` and `PhysicalMemoryCache` are all local to their compilation unit. (also true for enterprise) Just remove the declaration and everything should still work.

2023-04-04 09:33 UTC, maierlars commented on lib/Basics/NumberOfCores.h
> +};
This class is unimplemented. It is not the same class as `NumberOfCoresCache` defined in an anonymous namespace in `NumberOfCores.cpp`. It this declaration used anywhere?

2023-04-05 14:18 UTC, neunhoef requested changes
I think the determination of the database path is buggy. This needs to be fixed.

2023-04-05 14:18 UTC, neunhoef commented on lib/Basics/ArangoGlobalContext.cpp
> +  bool lastOptionName{false};
What is this magic for? What happens if the database directory is not given on the command line? Don't we have a DatabasePathFeature for this?

2023-04-05 14:18 UTC, neunhoef commented on lib/Basics/ArangoGlobalContext.cpp
> +  bool lastOptionName{false};
I also do not understand the logic with `lastOptionName`.

2023-04-05 14:18 UTC, neunhoef commented on lib/Basics/ArangoGlobalContext.cpp
> +  bool lastOptionName{false};
I think this is buggy.

2023-04-05 14:18 UTC, neunhoef commented on lib/Basics/ArangoGlobalContext.cpp
> +  bool lastOptionName{false};
At the very least it deserves an explanation.

2025-02-13 10:22 UTC, KVS85 commented
- [ ]

2025-02-13 10:22 UTC, closed without merging