SSO support on core web UI
arangodb/arangodb pull request #18723
Opened 2023-04-20 07:28 UTC by palashkaria

### Scope & Purpose

This adds hacky measures to handle SSO support on the web UI:
1. Logout button is disabled is SSO is enabled
2. We were using `jwtUser` set in sessionStorage during login. Since login is now skipped, we are using `/whoAmI` response to add that value

- [x] :pizza: New feature

### Checklist

- [x] Tests
  - [ ] Manually tested
- [ ] :book: CHANGELOG entry made

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-04-20 08:54 UTC, palashkaria commented
Moving back to draft as there might be some messaging changes

2023-04-25 11:42 UTC, ansoboleva requested changes
please see my comment

2023-04-25 11:42 UTC, ansoboleva commented on js/apps/system/_admin/aardvark/APP/frontend/js/templates/userBarView.ejs
> +        To log out of this DB, log out of the ArangoGraph.
Please change the message to "This login is automatically managed by ArangoGraph."

2023-04-25 12:58 UTC, nikhil-varma approved these changes

2023-04-25 12:58 UTC, nikhil-varma commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/userBarView.js
> +              var autoLoginEnabled = arangoHelper.getAutoLoginEnabled(autoLoginEnabled);
We can use `const` ?

2023-04-25 14:02 UTC, KVS85 requested changes
@ansoboleva @palashkaria

What will happen if there is a non-AG deployment with this header being set but not JWT token is provided?

What will happen to a a non-AG deployment with this header being set but no authentication enabled?

2023-04-25 14:27 UTC, palashkaria commented
> @ansoboleva @palashkaria
> 
> What will happen if there is a non-AG deployment with this header being set but not JWT token is provided?
> 
> What will happen to a a non-AG deployment with this header being set but no authentication enabled?


@KVS85 

- If this header is set, and you are logged in, you will see this:
![image (3)](https://user-images.githubusercontent.com/2976363/234308205-f63aab0a-3492-4b9d-b680-a42b9a74e2f8.png)

- If the header is set, and you are not logged in, you will be asked to log in.

This header is not dealing with authentication, it is only used to show/hide the logout button. The authentication (& setting of this header) is handled by the auth middleware on the AG side.

2023-04-25 22:30 UTC, KVS85 commented
- [ ] https://jenkins.arangodb.biz/job/arangodb-ANY-jslint/28594/

2023-04-25 23:54 UTC, merged