FE-162: Display geodesic lines instead in geo visualization
arangodb/arangodb pull request #18758
Opened 2023-04-25 13:04 UTC by ajurdak

### Scope & Purpose

This PR solves one of two geo visualization issues. With the added package "leaflet.geodesic" lines are now displayed geodesic and not straight.

For example `RETURN GEO_Polygon([[47.56, -122.33], [-33.94, 18.39], [39.92, 116.39], [48.2084114, 16.3708958], [47.56, -122.33]])` in the query editor in the WebUI the result looks now like this:
![image](https://user-images.githubusercontent.com/56896586/234865840-826f0c19-28be-4550-9064-648c0e232d43.png)

- [x] :hankey: Bugfix

### Checklist

- [x] Manually tested
- [x] :book: CHANGELOG entry made
- [ ] Backports
  - [x] Backport for 3.11: https://github.com/arangodb/arangodb/pull/18830
  - [ ] Backport for 3.10: ToDo

#### Related Information

- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-777

2023-04-26 11:17 UTC, palashkaria requested changes

2023-04-26 11:17 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/frontend/js/lib/leaflet.geodesic.js
why do we need to have this file in our source code? Can't we use the [npm package](https://www.npmjs.com/package/leaflet.geodesic) for this?

2023-04-26 11:17 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
> -                  geojson = new L.GeoJSON(geometry, {
is L.GeoJSON inbuilt, or was it another leaflet package? If it was and it's unused now, maybe we can remove it?

2023-04-27 09:55 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/frontend/js/lib/leaflet.geodesic.js
let's try using package.json for this new dependency @ajurdak

2023-04-27 10:16 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
> -                  geojson = new L.GeoJSON(geometry, {
I guess that specific package can still remain, but we can move others (like leaflet itself) to npm? Should work, but will need to try

2023-04-27 12:42 UTC, ajurdak commented on js/apps/system/_admin/aardvark/APP/frontend/js/lib/leaflet.geodesic.js
With eb2d1c963d42a01da8de69b8190d784775f01cf5

- package.json is used for the dependencies
- Unnecessary files are deleted

2023-04-27 13:06 UTC, palashkaria approved these changes
LGTM

2023-04-27 14:37 UTC, palashkaria commented
@ajurdak I just noticed, there are a lot of breaking changes between 1.3.3 to 1.9.3. Have you verified we are not using any of them?
https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md

2023-05-03 14:51 UTC, merged

2023-05-17 11:50 UTC, Simran-B commented
Looks like the example had longitude and latitude in the wrong order. This gives me the same result as in the screenshot:

`RETURN GEO_POLYGON([[-122.33, 47.56], [18.39, -33.94], [116.39, 39.92], [16.3708958, 48.2084114], [-122.33, 47.56]])`