Bug fix 3.10/MDS-1070 backport new iresearch
arangodb/arangodb pull request #18879
Opened 2023-05-08 14:23 UTC by Dronplane

### Scope & Purpose

This PR uses latest version of iresearch library adopted to use with 3.10 to fix consistency issues.

Enterprise Part: https://github.com/arangodb/enterprise/pull/1265

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-05-09 11:14 UTC, MBkkt requested changes

2023-05-09 11:14 UTC, MBkkt commented on arangod/IResearch/IResearchDataStore.h
>    bool _wasCommit = false;
You forgot to remove it. Now abort incorrect

2023-05-09 18:34 UTC, MBkkt approved these changes

2023-05-11 10:32 UTC, joerg84 approved these changes

2023-05-11 11:22 UTC, merged