[BTS-1350]
arangodb/arangodb pull request #18911
Opened 2023-05-10 04:51 UTC by cpjulia

### Scope & Purpose

 Fixed imprecision in index info in telemetrics object for cluster. When the collection also had an arangosearch view, telemetrics showed imprecise index values because the view was being considered as an index of type arangosearch, and its object wouldn't contain expected fields that would be found in other indexes' objects.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [x] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [x] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*
  - [ ] Backport for 3.8: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1350
- [ ] Design document:

2023-05-10 21:43 UTC, jsteemann commented on tests/js/client/server_parameters/test-telemetrics-true-auth.js
> +                assertTrue(nDocs === 0 || nDocs === 1);
```suggestion
                assertTrue(nDocs <= 1, nDocs);
```

2023-05-10 21:43 UTC, jsteemann commented on tests/js/client/server_parameters/test-telemetrics-true-auth.js
> +                assertTrue(nDocs === 0 || nDocs === 1);
```suggestion
                assertTrue(nDocs <= 1, nDocs);
```

2023-05-10 21:44 UTC, jsteemann commented on tests/js/client/server_parameters/test-telemetrics-true-auth.js
> +                assertTrue(nDocs === 0 || nDocs === 1);
```suggestion
                assertTrue(nDocs <= 1, nDocs);
```

2023-05-10 21:44 UTC, jsteemann commented on tests/js/client/server_parameters/test-telemetrics-true-auth.js
> +                assertTrue(nDocs === 0 || nDocs === 1);
```suggestion
                assertTrue(nDocs <= 1, nDocs);
```

2023-05-10 21:45 UTC, jsteemann commented on tests/js/client/server_parameters/test-telemetrics-true-auth.js
>          if (res.code === 420) {
https://httpstatusdogs.com/420-enhance-your-calm

2023-05-11 07:44 UTC, gnusi requested changes
We need information about links as well

2023-05-11 17:15 UTC, gnusi approved these changes

2023-05-11 18:08 UTC, jsteemann approved these changes
LGTM

2023-05-11 19:52 UTC, merged