Don't apply parallelize gather rule for one-shard DBs
arangodb/arangodb pull request #18998
Opened 2023-05-15 13:41 UTC by mpoeter

### Scope & Purpose

Enterprise companion: https://github.com/arangodb/enterprise/pull/1270

- [x] :hankey: Bugfix

### Checklist

- [x] Tests
  - [x] **Regression tests** - see enterprise companion
- [ ] Backports
  - [ ] Backport for 3.11: *(Please link PR)*

#### Related Information

- Jira ticket: https://arangodb.atlassian.net/browse/BTS-1402

2023-05-15 13:47 UTC, jsteemann approved these changes
LGTM

2023-05-16 06:27 UTC, mchacki approved these changes
In general LGTM.
Im unsure if this is enough or if we need a protection for "accidental" one shards.

2023-05-16 06:27 UTC, mchacki commented on arangod/Aql/OptimizerRules.cpp
> +  if (plan->getAst()->query().vocbase().isOneShard()) {
Does it hurt if it is applied? Or is this "just" unnecessary work?

If yes:
If we  are in a sharded database "by accident" have collections with only 1 shard, that are all on the same server we may apply a plan that looks similar to a oneShardDB plan.

2023-05-16 06:29 UTC, mchacki requested changes
Wait a second.
Can we have a test similar to the example in the BTS ticket?
Otherwise I cannot be sure that we actually fix something, I am not fully convinced that parallel gather causes the BTS query to "fail"

2023-05-16 12:07 UTC, mpoeter commented
As it turned out the referenced BTS issue has a different root cause - thus closing this.

2023-05-16 12:07 UTC, closed without merging