Fix issues in BTS-1255
arangodb/arangodb pull request #19093
Opened 2023-05-24 20:58 UTC by jsteemann

### Scope & Purpose

Fix most issues described in https://arangodb.atlassian.net/browse/BTS-1255

* BTS-1255: Fix sporadic memory usage accounting underflows in in-memory cache subsystem. Also turn the algorithm for freeing memory from a cache's buckets from a non-deterministic one that did not guarantee progress into a bounded algorithm with guaranteed progress.

  Also enable 2 previously disabled tests because they are now stable after the fixes.

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.11: -
  - [ ] Backport for 3.10: -
  - [ ] Backport for 3.9: -

#### Related Information

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1255
- [ ] Design document:

2023-05-24 21:54 UTC, kvahed approved these changes
LGTM

2023-05-25 09:15 UTC, mpoeter requested changes
I really don't like the code duplication the whole byId/byHash separation introduces. Can we avoid that?

2023-05-25 11:03 UTC, jsteemann commented on arangod/Cache/Manager.cpp
> +    metaGuard.release();
Fixed

2023-05-25 11:05 UTC, jsteemann commented on arangod/Cache/Manager.cpp
> +    }
Fixed

2023-05-25 11:05 UTC, jsteemann commented on arangod/Cache/Cache.cpp
> +    if (++attempts % 32 == 0 && isShutdown()) {
Fixed

2023-05-25 13:04 UTC, mpoeter commented on arangod/Cache/PlainCache.cpp
> +    requestMigrate(table->idealSizeValue());
That's fine, I was just wondering whether we can find a better name that actually describes what the function is doing (including its side effects).

2023-05-25 20:33 UTC, jsteemann commented on arangod/Cache/PlainCache.cpp
> +    requestMigrate(table->idealSizeValue());
I have been looking at the existing `idealSize()` method for 5 minutes now and cannot come up with a better name.
It is unfortunate that it has side-effects, but I decided against changing that for this PR.
I can't come up with a better name right now, unfortunately, so I vote for leaving the name as is for now.
There are code comments on each call site now that warn about the call's potential side-effects.

2023-05-26 10:39 UTC, mpoeter approved these changes

2023-05-26 18:17 UTC, kvahed approved these changes
LGTM

2023-05-30 09:26 UTC, merged