[FE-20] Implement locale placeholder
arangodb/arangodb pull request #19127
Opened 2023-05-30 17:45 UTC by pluma4345

### Scope & Purpose

This PR changes the `LocaleInput` to take an additional `placeholder` property and changes the placeholders for each analyzer type to a correct format.

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [x] Backport for 3.11: #19128
  - [x] Backport for 3.10: #19129
  - [ ] Backport for 3.9: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: FE-20
- [ ] Design document:

2023-06-07 10:27 UTC, palashkaria approved these changes
LGTM

2023-06-09 11:22 UTC, Dronplane commented
One question - why for different analyzers locale placeholders looks different?  I'd expecte to have just one placeholder for any analyzers that use locale.

2023-06-09 12:48 UTC, Dronplane requested changes
Checked the code. Actual usage should be like this. @Simran-B it would be also good to have same changes in the documentation

2023-06-09 12:48 UTC, Dronplane commented on js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/NormForm.tsx
> +                   placeholder="language[_COUNTRY]" disabled={disabled}/>
```suggestion
                   placeholder="language[_COUNTRY][_VARIANT]" disabled={disabled}/>
```

2023-06-09 12:48 UTC, Dronplane commented on js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/TextForm.tsx
> +                       placeholder="language[_COUNTRY]" disabled={disabled}/>
```suggestion
                       placeholder="language[_COUNTRY][_VARIANT]" disabled={disabled}/>
```

2023-06-09 18:19 UTC, pluma commented
@Dronplane @Simran-B The PR is implemented in accordance with the placeholder formats specified in the ticket FE-20. Is the ticket wrong?

2023-06-14 11:24 UTC, Simran-B commented
norm and text do indeed accept `_VARIANT`

2023-06-20 22:45 UTC, ajurdak approved these changes
LGTM.

2023-06-21 12:59 UTC, Dronplane approved these changes
LGTM

2023-06-22 10:53 UTC, merged