[FE-229] improve shard rebalancing UI
arangodb/arangodb pull request #19241
Opened 2023-06-14 09:49 UTC by pluma4345

### Scope & Purpose

- [ ] :hankey: Bugfix
- [x] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.11: *(Please link PR)*
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: FE-229
- [ ] Design document: 

![image](https://github.com/arangodb/arangodb/assets/109235316/78d01bcb-88ab-40cf-a16d-95a423067e69)

2023-06-14 15:57 UTC, palashkaria requested changes

2023-06-14 15:57 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/RebalanceShards.tsx
> +      window.arangoHelper.arangoNotification('Rebalanced shards with ' + result.moves.length + ' move operation(s).');
maybe we can prefer template strings here?

```suggestion
      window.arangoHelper.arangoNotification(`Rebalanced shards with ${result.moves.length} move operation(s).`);
```

2023-06-14 15:57 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/RebalanceShards.tsx
> +            display={"grid"}
Can use Grid from chakra
```suggestion
          <Grid
```

2023-06-14 15:57 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/RebalanceShards.tsx
> +          <Box fontSize={"lg"}>
Can use Text from Chakra
```suggestion
          <Text fontSize={"lg"}>
```

2023-06-14 15:57 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
> +          React.createElement(ShardDistributionReactView, {
```suggestion
          React.createElement(window.ShardDistributionReactView, {
```

2023-06-14 15:57 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/RebalanceShards.tsx
as discussed, let's ensure we do prettier formatting for all new files

2023-06-15 11:02 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/AddIndexForm.tsx
> +import { InvertedIndexFormWrap } from "./invertedIndex/InvertedIndexFormWrap";
I mostly run organize imports, possible that I could've missed it here. But even then - "Z" should be last, and "I" should be above "P"? (as it already was?)

2023-06-19 10:48 UTC, ajurdak approved these changes
I reviewed the code as well as the UI itself. Great work.
LGTM.

2023-06-21 11:04 UTC, palashkaria reviewed
LGTM!

2023-06-21 11:04 UTC, palashkaria approved these changes

2023-06-22 14:28 UTC, merged