WIP APM-668 Search memory accounting
arangodb/arangodb pull request #19388
Opened 2023-07-06 12:34 UTC by MBkkt

### Scope & Purpose

WIP

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.11: *(Please link PR)*
  - [ ] Backport for 3.10: *(Please link PR)*
  - [ ] Backport for 3.9: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-07-10 11:44 UTC, Dronplane requested changes

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_consolidations_memory.yaml
> +  Count of memory in bytes that used for consolidate this index.
```suggestion
  Count of memory in bytes that is used for consolidating this index.
```

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_consolidations_memory.yaml
> +  Count of memory in bytes that used for consolidate this index.
```suggestion
  Count of memory in bytes that is used for consolidating this index.
```

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_writers_memory.yaml
> +  Count of memory in bytes that used for write in this index.
```suggestion
  Count of memory in bytes that is used for writing to this index.
```

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_readers_memory.yaml
> +name: arangodb_search_writers_memory
```suggestion
name: arangodb_search_readers_memory
```

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_readers_memory.yaml
> +  Count of memory in bytes that used for read from this index.
```suggestion
  Count of memory in bytes that is used for reading from this index.
```

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_readers_memory.yaml
> +  Count of memory in bytes that used for read from this index.
```suggestion
  Count of memory in bytes that is used for reading from this index.
```

2023-07-10 11:44 UTC, Dronplane commented on Documentation/Metrics/arangodb_search_writers_memory.yaml
> +  Count of memory in bytes that used for write in this index.
```suggestion
  Count of memory in bytes that is used for writing to this index.
```

2023-07-10 11:50 UTC, Dronplane commented on arangod/IResearch/IResearchFeature.h
> +  irs::IResourceManager& _columnsCacheMemoryUsed;
Should this reference be initialized somehow?

2023-07-10 11:50 UTC, Dronplane commented on arangod/IResearch/IResearchMetricStats.h
> +
accidental edit?

2023-07-10 11:50 UTC, Dronplane commented on arangod/IResearch/ResourceManager.hpp
> +struct LimittedResourceManager final : metrics::Gauge<uint64_t>,
```suggestion
struct LimitedResourceManager final : metrics::Gauge<uint64_t>,
```
Double `t` in the name looks like a typo

2023-07-11 21:12 UTC, Dronplane reviewed
One test case is missing

2023-07-11 23:18 UTC, MBkkt commented on tests/js/client/shell/api/arangosearch-memory-metrics-noncluster.js
> +      let c = db._collection(collection);
Needs to fix API in iresearch.
It's not part of APM ticket, so I suggest to fix it separate PR.

2023-07-12 12:12 UTC, MBkkt commented on tests/js/client/shell/api/arangosearch-memory-metrics-noncluster.js
> +      let c = db._collection(collection);
Done

2023-07-12 14:55 UTC, merged