[BTS-1553][3.9] Fix wrong limit value use in LimitExecutor
arangodb/arangodb pull request #19602
Opened 2023-08-15 13:42 UTC by hkernbach

### Scope & Purpose

3.9 Backport of: https://github.com/arangodb/arangodb/pull/19592
See details there.

2023-08-16 15:15 UTC, mchacki approved these changes
LGTM

2023-08-17 08:55 UTC, mpoeter requested changes
Changelog entry is missing

2023-08-17 08:55 UTC, mpoeter commented on tests/Aql/LimitExecutorTest.cpp
> +      // Note that fullCount does only make sense with a hard limit, and
Comment is cut off mid-sentence

2023-08-17 09:22 UTC, hkernbach commented on tests/Aql/LimitExecutorTest.cpp
> +      // Note that fullCount does only make sense with a hard limit, and
Thanks resolved.

2023-08-21 08:56 UTC, mpoeter approved these changes

2023-08-21 09:12 UTC, merged