[CINFRA-810] Migrate replicated log tests
arangodb/arangodb pull request #19814
Opened 2023-09-25 13:01 UTC by goedderz

### Scope & Purpose

Introduce a new testing framework for replicated logs, and use it to migrate the following test suites, which are currently disabled:

-  ReplicatedLog/AppendEntriesBatchTest.cpp
-  ReplicatedLog/LeaderAppendEntriesTest.cpp
-  ReplicatedLog/MultiTermTest.cpp
-  ReplicatedLog/RewriteLogTest.cpp

The following files are still disabled, and to be migrated in a later PR:

- ReplicatedLog/ConcurrencyTests.cpp
- ReplicatedLog/SimpleInsertTests.cpp
- ReplicatedLog/UpdateParticipantsFlags.cpp
- ReplicatedLog/WaitForSyncTest.cpp

2023-10-03 16:45 UTC, apetenchea requested changes
Apart from my comment regarding `std::remove_if`, the rest are more or less nitpicks.

2023-10-04 08:27 UTC, goedderz commented on tests/Replication2/CMakeLists.txt
> +# decide whether to fix it or remove it. [tobias, 2023-08-10]
Opened a ticket: https://arangodb.atlassian.net/browse/CINFRA-850

2023-10-04 08:47 UTC, goedderz commented on tests/Replication2/Helper/ReplicatedLogTestSetup.h
> +    auto const leader = std::dynamic_pointer_cast<replicated_log::ILogLeader>(
I don't think it's moved in the return, there should be a copy elision / RVO, which I think should be unaffected by the `const`. I've applied your suggestion anyway.

2023-10-04 08:47 UTC, goedderz commented on tests/Replication2/Helper/ReplicatedLogTestSetup.h
> +               : std::nullopt;
Right, thanks for spotting.

2023-10-04 08:47 UTC, goedderz commented on tests/Replication2/Helper/ReplicatedLogTestSetup.h
> +                       shouldBeRemoved);
:see_no_evil: Of course. Thanks for noticing!

2023-10-04 08:48 UTC, goedderz commented on tests/Replication2/ReplicatedLog/MultiTermTest.cpp
> +    std::swap(oldScheduler, *followerLogContainer->logScheduler);
Right, that happened due to incremental changes regarding this. Thanks, it's cleaner now.

2023-10-04 09:00 UTC, apetenchea approved these changes
LGTM

2024-01-09 14:00 UTC, goedderz commented on tests/Replication2/Mocks/DelayedLogFollower.h
> +  auto runAsyncAppendEntries() -> std::size_t;
Not necessarily.

2024-01-09 14:02 UTC, goedderz commented
> LGTM
> 
> I am wondering if we can work around this concept issue in IHasScheduler though...

I haven't found a way in the time I invested - and I think waiting for a recent enough compiler is fine, this will just solve itself.

2024-01-10 14:03 UTC, merged