Silence TSAN w.r.t. SCHEDULER pointer on shutdown
arangodb/arangodb pull request #20065
Opened 2023-11-03 13:48 UTC by neunhoef

### Scope & Purpose

This is a backport of https://github.com/arangodb/arangodb/pull/20056 .

This addresses https://arangodb.atlassian.net/browse/BTS-1671.

It is to silence TSAN in some shutdown cases in RTA.

There is a global pointer called SchedulerFeature::SCHEDULER. On
shutdown, we set this pointer to nullptr in the
SchedulerFeature::unprepare method. In various other places, we read out
the pointer.

The logic of ApplicationFeatures should ensure that nobody will read
the pointer out after the SchedulerFeature has run its unprepare
method. Sometimes the TSAN sanitizer cannot recognize this indirect
synchronization and complains about reads that have happened before the
write there, but are not officially inter-thread synchronized. We use
atomic references in some places to silence TSAN.

- [*] :hankey: Bugfix

### Checklist

- [*] :book: CHANGELOG entry made
- [*] Backports
  - [*] Backport for 3.10: This is it.

#### Related Information

- [*] GitHub issue / Jira ticket: https://arangodb.atlassian.net/browse/BTS-1671
- [*] Devel PR: https://github.com/arangodb/arangodb/pull/20056

2023-11-03 16:15 UTC, dothebart approved these changes

2023-11-07 08:38 UTC, mpoeter approved these changes

2023-11-08 11:43 UTC, KVS85 requested changes
macOS compilation is broken. Please see https://jenkins.arangodb.biz/job/arangodb-matrix-pr-mac-onlycatch.x86-64/26252/EDITION=community,limit=mac&&test&&x86-64/artifact/buildArangoDB.log.

2023-11-08 13:36 UTC, neunhoef commented
atomic_ref is not supported by Apple Clang, we need this still in 3.10. Giving up on this, closing the PR.

2023-11-08 13:36 UTC, closed without merging