APM-822 Feature/apm 822 add metric for threads usage
arangodb/arangodb pull request #20074
Opened 2023-11-06 13:56 UTC by Dronplane

### Scope & Purpose
PR adds metric to expose number of active threads.

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.11: *(Please link PR)*
  - [ ] Backport for 3.10: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-11-06 15:00 UTC, Dronplane commented
https://172.26.1.0/view/PR/job/arangodb-matrix-pr/32014/

2023-11-07 11:14 UTC, MBkkt reviewed
I don't think it's needed and also I don't see any mention in APM-822.
So I think this shouldn't be done

2023-11-07 11:15 UTC, MBkkt requested changes
I don't think it's needed and also I don't see any mention in APM-822.
So I think this shouldn't be done

2023-11-07 11:19 UTC, MBkkt commented on arangod/IResearch/IResearchExecutionPool.cpp
> +  }
here can be added warn/info message about we don't have enough threads.

2023-11-07 11:22 UTC, Dronplane commented
> I don't think it's needed and also I don't see any mention in APM-822. So I think this shouldn't be done

I don't agree. We need to provide visibility to our customers. Using "htop"-like utility would not help as we are planning to use pool with pre-forked threads. So there would be no way to estimate if parallelism is used and if used  how actively.

2023-11-07 14:22 UTC, MBkkt commented
Well, I don't have better option.

But this approach also isn't option, because metrics especially with current value doesn't suite for this.

Honestly I'm not really sure why do we need provide such information at all, we don't make it for other concurrent activities, why for this?

2023-11-07 14:30 UTC, Dronplane commented
> because metrics especially with current value doesn't suite for this.
Why? 
> I'm not really sure why do we need provide such information at all, we don't make it for other concurrent activities, why for this?
You are wrong. There is  for example `arangodb_scheduler_num_awake_threads` metrics  and `arangodb_pregel_threads_number` and 'arangodb_scheduler_num_worker_threads' and so on

2023-11-09 13:29 UTC, Dronplane commented
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/32049/

2023-11-09 15:19 UTC, merged