3.10 adjustments for clang-16
arangodb/arangodb pull request #20338
Opened 2023-12-19 11:34 UTC by kvahed

### Scope & Purpose

*3.10 adjustments for clang-16*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [ ] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.11: *(Please link PR)*
  - [ ] Backport for 3.10: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [ ] GitHub issue / Jira ticket:
- [ ] Design document:

2023-12-19 13:59 UTC, MBkkt reviewed
Also making abseil submodule require these lines before add_subdirectory(...)

```
UpdateModule(${GIT_EXECUTABLE} "abseil-cpp" ${CMAKE_CURRENT_SOURCE_DIR} "README.md")

set(ABSL_PROPAGATE_CXX_STD ON)
```

2023-12-19 13:59 UTC, MBkkt commented on 3rdParty/s2geometry/CMakeLists.txt
> +add_subdirectory(${ARANGO_S2GEOMETRY_VERSION})
It's not correct without this https://github.com/arangodb/arangodb/blob/devel/CMakeLists.txt#L1190

2024-01-09 12:14 UTC, KVS85 requested changes
clang isn't used as a production compiler for 3.10.

2024-01-16 14:32 UTC, MBkkt requested changes
Check my previous comments

2024-02-01 13:53 UTC, closed without merging