Improve sanitizer builds
arangodb/arangodb pull request #20649
Opened 2024-02-22 16:12 UTC by mpoeter

### Scope & Purpose

Enterprise companion https://github.com/arangodb/enterprise/pull/1453

This PR disables some long running/memory intensive tests for tsan and also improves some tests to use babies operations.

2024-02-26 16:42 UTC, dothebart requested changes
please don't skip inside testfiles. 
Files should be ruled out by suffixes so its clearly visible they won't be executed under certain circumstances.

2024-02-26 16:42 UTC, dothebart commented on tests/js/client/aql/aql-index-cache.js
> +if (!isCluster || (!versionHas('asan') && !versionHas('tsan'))) {
No magic execution blocks inside testfiles!
Use filename extensions `-noasan` and `-noncluster`

2024-02-27 10:27 UTC, dothebart approved these changes
LGTM.

2024-02-27 12:54 UTC, mpoeter commented on tests/js/client/aql/aql-index-cache-noinstr_or_noncluster.js
> +const versionHas = require("@arangodb/test-helper").versionHas;
```suggestion
```

2024-02-27 13:31 UTC, merged