[FE-450] Avoid unncessary scrollbars when license warning is visible
arangodb/arangodb pull request #21350
Opened 2024-10-08 13:48 UTC by pluma4345

### Scope & Purpose

*(Please describe the changes in this PR for reviewers, motivation, rationale - **mandatory**)*

- [x] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] Tests
  - [ ] **Regression tests**
  - [ ] C++ **Unit tests**
  - [ ] **integration tests**
  - [ ] **resilience tests**
- [x] :book: CHANGELOG entry made
- [ ] :books: documentation written (release notes, API changes, ...)
- [ ] Backports
  - [ ] Backport for 3.12.0: *(Please link PR)*
  - [ ] Backport for 3.11: *(Please link PR)*
  - [ ] Backport for 3.10: *(Please link PR)*

#### Related Information

*(Please reference tickets / specification / other PRs etc)*

- [ ] Docs PR: 
- [ ] Enterprise PR:
- [x] GitHub issue / Jira ticket: FE-450
- [ ] Design document:

2024-10-16 10:55 UTC, palashkaria requested changes

2024-10-16 10:55 UTC, palashkaria commented on js/apps/system/_admin/aardvark/APP/react/src/views/useNavbarHeight.ts
> +  console.log('height', height)
might want to remove this stray `console.log`

2024-10-21 10:20 UTC, shd8 approved these changes

2024-10-22 10:05 UTC, palashkaria approved these changes
LGTM!

2024-10-23 11:15 UTC, merged