Fix data race in async test
arangodb/arangodb pull request #21468
Opened 2024-11-21 09:42 UTC by jvolmer

Fixes data race shown in [CI](https://app.circleci.com/pipelines/github/arangodb/arangodb/31259/workflows/1e2964fc-e222-419a-b405-13a183e22b66/jobs/2577805/artifacts).
Make sure that coroutine lives long enough to be resumed

2024-11-21 09:53 UTC, dothebart approved these changes

2024-11-21 14:42 UTC, maierlars requested changes
While is might be a fix, I think there is a bigger problem. How can dropping `a` in `waiter_fn` cause any problems? The coroutine promise shouldn't be destroyed unless both sides of the coroutine are done. Happy to be convinced otherwise 🤔

2024-11-26 14:10 UTC, jvolmer commented on lib/Async/include/Async/async.h
> +        outer_promise->update_state(async_registry::State::Suspended);
https://github.com/arangodb/arangodb/pull/21468

2024-11-26 14:18 UTC, jvolmer commented
I think the memory order used when resetting was not correct: 

It happend in `AsyncTest::async_promises_in_async_registry_know_their_requester_with_move_and_call_without_await` with WaitType `ConcurrentNoWait`.
The tsan issue occurred because one thread (the extra thread started inside `ConcurrentNoWait`) resumes the coroutine `awaited_2_fn` but at the same time the variable that holds `awaited_2_fn` (called `a`) goes out of scope, calling `reset()` on the coroutine and therefore `destroy()` on its handle. We use an atomic `continuation` for such synchronization of async coroutine calls between threads, but the defined memory order used inside `reset` was not correct: In the atomic exchange we used only aquire which can result in read and write reorderings after this exchange although we need to synchronize with the exchange used in the `final_suspend::await_suspend` which can happen afterwards.

2024-11-27 09:26 UTC, dothebart approved these changes

2024-11-27 10:28 UTC, goedderz approved these changes

2024-11-27 13:54 UTC, merged