add array destructuring to AQL
arangodb/arangodb pull request #4718
Opened 2018-03-01 09:02 UTC by jsteemann

This allows using a nicer syntax for parsing the members of an array into separate AQL variables.
Recursive destructuring is also supported

Example query that will demonstrate the new functionality:

    LET a = ["foo", "bar", "baz", [1, 2, 3], false, "meow"]
    LET [foo, bar, baz, [sub1, , sub3], , meow] = a
    RETURN { foo, bar, baz, sub1, sub3, meow }

This will return

    [
      {
	"foo" : "foo",
	"bar" : "bar",
	"baz" : "baz",
	"sub1" : 1,
	"sub3" : 3,
	"meow" : "meow"
      }
    ]

2018-07-21 18:05 UTC, dsonet commented
Very useful, would like to see this feature.

2018-07-24 10:12 UTC, jsteemann commented
It seems that it works already, but it is obviously missing tests.

2019-01-21 15:53 UTC, jsteemann commented
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/2806/

2019-03-11 11:13 UTC, Simran-B requested changes
Added suggestions to improve the docs. Spreading and destructuring also need to be explained in the regular documentation - shall I do the required changes in this PR?

2019-03-11 11:19 UTC, jsteemann commented on Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
> +    RETURN { id: "1234", age: 39, ...obj, active: true }
Ok, thanks for the hint. I have used your suggestion in the NewFeatures35.md file.

2019-03-11 11:19 UTC, jsteemann commented
@Simran-B : please feel free to adjust the manual as you see fit!

2019-03-12 16:12 UTC, Simran-B commented
Object spreading doesn't behave as I expected. In JavaScript:

```js
console.log(JSON.stringify( {
  foo: 1, bar: 2,
  ...{baz: 3, foo:4, new: 5, nested: {sub: 6} },
  ...{new: 7, nested: {sub: 8} }
} ));
// { "foo": 4, "bar": 2, "baz": 3, "new": 7, "nested": { "sub": 8} }
```

In AQL I got:

```js
RETURN {
  foo: 1, bar: 2,
  ...{baz: 3, foo:4, new: 5, nested: {sub: 6} },
  ...{new: 7, nested: {sub: 8} }
}
// { "foo": 1, "bar": 2, "baz": 3, "new": 5, "nested": { "sub": 6 } }
```

Looks like the first value wins? That also raised the question whether object spreading is equivalent to MERGE() or rather MERGE_RECURSIVE(), but currently it seems to be neither.

2019-03-12 16:26 UTC, jsteemann commented
@Simran-B : AQL does not support overwriting existing attributes. The exceptions here may be MERGE and MERGE_RECURSIVE. However, any other places keep the first value of each attribute and don't attribute it.

2019-03-12 18:21 UTC, Simran-B commented
@jsteemann I know that literals like `{a: 1, a: 2}` lead to `{ a: 1 }`, which is different to the behavior of JavaScript, but acceptable. If `...{ }` does that however, then that seems really counter-intuitive. I would bet that many JS users don't know by heart what you end up with if you specify the same key in an object literal twice, but if they know the object spread operator then I'm sure they know that the value of the key specified last wins.

The current documentation is also wrong because it states that it would be the same as `MERGE()`, which it is not. It is rather like MERGE_RECURSIVE(), but with the arguments reversed (I think?)

Would it be difficult to change the behavior? Could the expressions be reversed internally so that "first key wins" doesn't get in the way?

2023-05-30 10:40 UTC, closed without merging